# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pyatv/mrp/protobuf/CommandOptions.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pyatv/mrp/protobuf/CommandOptions.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\'pyatv/mrp/protobuf/CommandOptions.proto\"\xbc\x06\n\x0e\x43ommandOptions\x12\x10\n\x08sourceId\x18\x02 \x01(\t\x12\x11\n\tmediaType\x18\x03 \x01(\t\x12\x1d\n\x15\x65xternalPlayerCommand\x18\x04 \x01(\x08\x12\x14\n\x0cskipInterval\x18\x05 \x01(\x02\x12\x14\n\x0cplaybackRate\x18\x06 \x01(\x02\x12\x0e\n\x06rating\x18\x07 \x01(\x02\x12\x10\n\x08negative\x18\x08 \x01(\x08\x12\x18\n\x10playbackPosition\x18\t \x01(\x01\x12\x12\n\nrepeatMode\x18\n \x01(\x05\x12\x13\n\x0bshuffleMode\x18\x0b \x01(\x05\x12\x0f\n\x07trackID\x18\x0c \x01(\x04\x12\x16\n\x0eradioStationID\x18\r \x01(\x03\x12\x18\n\x10radioStationHash\x18\x0e \x01(\t\x12\"\n\x1asystemAppPlaybackQueueData\x18\x0f \x01(\x0c\x12\x1f\n\x17\x64\x65stinationAppDisplayID\x18\x10 \x01(\t\x12\x13\n\x0bsendOptions\x18\x11 \x01(\r\x12/\n\'requestDefermentToPlaybackQueuePosition\x18\x12 \x01(\x08\x12\x11\n\tcontextID\x18\x13 \x01(\t\x12*\n\"shouldOverrideManuallyCuratedQueue\x18\x14 \x01(\x08\x12\x12\n\nstationURL\x18\x15 \x01(\t\x12 \n\x18shouldBeginRadioPlayback\x18\x16 \x01(\x08\x12&\n\x1eplaybackQueueInsertionPosition\x18\x17 \x01(\x05\x12\x15\n\rcontentItemID\x18\x18 \x01(\t\x12\x1b\n\x13playbackQueueOffset\x18\x19 \x01(\x05\x12&\n\x1eplaybackQueueDestinationOffset\x18\x1a \x01(\x05\x12\x16\n\x0elanguageOption\x18\x1b \x01(\x0c\x12\x1c\n\x14playbackQueueContext\x18\x1c \x01(\x0c\x12 \n\x18insertAfterContentItemID\x18\x1d \x01(\t\x12\x1f\n\x17nowPlayingContentItemID\x18\x1e \x01(\t\x12\x15\n\rreplaceIntent\x18\x1f \x01(\x05')
)




_COMMANDOPTIONS = _descriptor.Descriptor(
  name='CommandOptions',
  full_name='CommandOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sourceId', full_name='CommandOptions.sourceId', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mediaType', full_name='CommandOptions.mediaType', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='externalPlayerCommand', full_name='CommandOptions.externalPlayerCommand', index=2,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='skipInterval', full_name='CommandOptions.skipInterval', index=3,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='playbackRate', full_name='CommandOptions.playbackRate', index=4,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rating', full_name='CommandOptions.rating', index=5,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='negative', full_name='CommandOptions.negative', index=6,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='playbackPosition', full_name='CommandOptions.playbackPosition', index=7,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='repeatMode', full_name='CommandOptions.repeatMode', index=8,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shuffleMode', full_name='CommandOptions.shuffleMode', index=9,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trackID', full_name='CommandOptions.trackID', index=10,
      number=12, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='radioStationID', full_name='CommandOptions.radioStationID', index=11,
      number=13, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='radioStationHash', full_name='CommandOptions.radioStationHash', index=12,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='systemAppPlaybackQueueData', full_name='CommandOptions.systemAppPlaybackQueueData', index=13,
      number=15, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='destinationAppDisplayID', full_name='CommandOptions.destinationAppDisplayID', index=14,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sendOptions', full_name='CommandOptions.sendOptions', index=15,
      number=17, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='requestDefermentToPlaybackQueuePosition', full_name='CommandOptions.requestDefermentToPlaybackQueuePosition', index=16,
      number=18, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='contextID', full_name='CommandOptions.contextID', index=17,
      number=19, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shouldOverrideManuallyCuratedQueue', full_name='CommandOptions.shouldOverrideManuallyCuratedQueue', index=18,
      number=20, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stationURL', full_name='CommandOptions.stationURL', index=19,
      number=21, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shouldBeginRadioPlayback', full_name='CommandOptions.shouldBeginRadioPlayback', index=20,
      number=22, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='playbackQueueInsertionPosition', full_name='CommandOptions.playbackQueueInsertionPosition', index=21,
      number=23, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='contentItemID', full_name='CommandOptions.contentItemID', index=22,
      number=24, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='playbackQueueOffset', full_name='CommandOptions.playbackQueueOffset', index=23,
      number=25, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='playbackQueueDestinationOffset', full_name='CommandOptions.playbackQueueDestinationOffset', index=24,
      number=26, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='languageOption', full_name='CommandOptions.languageOption', index=25,
      number=27, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='playbackQueueContext', full_name='CommandOptions.playbackQueueContext', index=26,
      number=28, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='insertAfterContentItemID', full_name='CommandOptions.insertAfterContentItemID', index=27,
      number=29, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nowPlayingContentItemID', full_name='CommandOptions.nowPlayingContentItemID', index=28,
      number=30, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='replaceIntent', full_name='CommandOptions.replaceIntent', index=29,
      number=31, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=872,
)

DESCRIPTOR.message_types_by_name['CommandOptions'] = _COMMANDOPTIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CommandOptions = _reflection.GeneratedProtocolMessageType('CommandOptions', (_message.Message,), dict(
  DESCRIPTOR = _COMMANDOPTIONS,
  __module__ = 'pyatv.mrp.protobuf.CommandOptions_pb2'
  # @@protoc_insertion_point(class_scope:CommandOptions)
  ))
_sym_db.RegisterMessage(CommandOptions)


# @@protoc_insertion_point(module_scope)
