# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pyatv/mrp/protobuf/CryptoPairingMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import ProtocolMessage_pb2 as pyatv_dot_mrp_dot_protobuf_dot_ProtocolMessage__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pyatv/mrp/protobuf/CryptoPairingMessage.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n-pyatv/mrp/protobuf/CryptoPairingMessage.proto\x1a(pyatv/mrp/protobuf/ProtocolMessage.proto\";\n\x14\x43ryptoPairingMessage\x12\x13\n\x0bpairingData\x18\x01 \x02(\x0c\x12\x0e\n\x06status\x18\x02 \x02(\x05:E\n\x14\x63ryptoPairingMessage\x12\x10.ProtocolMessage\x18\' \x01(\x0b\x32\x15.CryptoPairingMessage')
  ,
  dependencies=[pyatv_dot_mrp_dot_protobuf_dot_ProtocolMessage__pb2.DESCRIPTOR,])


CRYPTOPAIRINGMESSAGE_FIELD_NUMBER = 39
cryptoPairingMessage = _descriptor.FieldDescriptor(
  name='cryptoPairingMessage', full_name='cryptoPairingMessage', index=0,
  number=39, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None, file=DESCRIPTOR)


_CRYPTOPAIRINGMESSAGE = _descriptor.Descriptor(
  name='CryptoPairingMessage',
  full_name='CryptoPairingMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pairingData', full_name='CryptoPairingMessage.pairingData', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='CryptoPairingMessage.status', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=150,
)

DESCRIPTOR.message_types_by_name['CryptoPairingMessage'] = _CRYPTOPAIRINGMESSAGE
DESCRIPTOR.extensions_by_name['cryptoPairingMessage'] = cryptoPairingMessage
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CryptoPairingMessage = _reflection.GeneratedProtocolMessageType('CryptoPairingMessage', (_message.Message,), dict(
  DESCRIPTOR = _CRYPTOPAIRINGMESSAGE,
  __module__ = 'pyatv.mrp.protobuf.CryptoPairingMessage_pb2'
  # @@protoc_insertion_point(class_scope:CryptoPairingMessage)
  ))
_sym_db.RegisterMessage(CryptoPairingMessage)

cryptoPairingMessage.message_type = _CRYPTOPAIRINGMESSAGE
pyatv_dot_mrp_dot_protobuf_dot_ProtocolMessage__pb2.ProtocolMessage.RegisterExtension(cryptoPairingMessage)

# @@protoc_insertion_point(module_scope)
