# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pyatv/mrp/protobuf/NowPlayingPlayer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pyatv/mrp/protobuf/NowPlayingPlayer.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n)pyatv/mrp/protobuf/NowPlayingPlayer.proto\"T\n\x10NowPlayingPlayer\x12\x12\n\nidentifier\x18\x01 \x01(\t\x12\x13\n\x0b\x64isplayName\x18\x02 \x01(\t\x12\x17\n\x0fisDefaultPlayer\x18\x03 \x01(\x08')
)




_NOWPLAYINGPLAYER = _descriptor.Descriptor(
  name='NowPlayingPlayer',
  full_name='NowPlayingPlayer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='identifier', full_name='NowPlayingPlayer.identifier', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='displayName', full_name='NowPlayingPlayer.displayName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isDefaultPlayer', full_name='NowPlayingPlayer.isDefaultPlayer', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=129,
)

DESCRIPTOR.message_types_by_name['NowPlayingPlayer'] = _NOWPLAYINGPLAYER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NowPlayingPlayer = _reflection.GeneratedProtocolMessageType('NowPlayingPlayer', (_message.Message,), dict(
  DESCRIPTOR = _NOWPLAYINGPLAYER,
  __module__ = 'pyatv.mrp.protobuf.NowPlayingPlayer_pb2'
  # @@protoc_insertion_point(class_scope:NowPlayingPlayer)
  ))
_sym_db.RegisterMessage(NowPlayingPlayer)


# @@protoc_insertion_point(module_scope)
