# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pyatv/mrp/protobuf/SetHiliteModeMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import ProtocolMessage_pb2 as pyatv_dot_mrp_dot_protobuf_dot_ProtocolMessage__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pyatv/mrp/protobuf/SetHiliteModeMessage.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n-pyatv/mrp/protobuf/SetHiliteModeMessage.proto\x1a(pyatv/mrp/protobuf/ProtocolMessage.proto\"*\n\x14SetHiliteModeMessage\x12\x12\n\nhiliteMode\x18\x01 \x01(\x05:E\n\x14setHiliteModeMessage\x12\x10.ProtocolMessage\x18, \x01(\x0b\x32\x15.SetHiliteModeMessage')
  ,
  dependencies=[pyatv_dot_mrp_dot_protobuf_dot_ProtocolMessage__pb2.DESCRIPTOR,])


SETHILITEMODEMESSAGE_FIELD_NUMBER = 44
setHiliteModeMessage = _descriptor.FieldDescriptor(
  name='setHiliteModeMessage', full_name='setHiliteModeMessage', index=0,
  number=44, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None, file=DESCRIPTOR)


_SETHILITEMODEMESSAGE = _descriptor.Descriptor(
  name='SetHiliteModeMessage',
  full_name='SetHiliteModeMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hiliteMode', full_name='SetHiliteModeMessage.hiliteMode', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=133,
)

DESCRIPTOR.message_types_by_name['SetHiliteModeMessage'] = _SETHILITEMODEMESSAGE
DESCRIPTOR.extensions_by_name['setHiliteModeMessage'] = setHiliteModeMessage
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SetHiliteModeMessage = _reflection.GeneratedProtocolMessageType('SetHiliteModeMessage', (_message.Message,), dict(
  DESCRIPTOR = _SETHILITEMODEMESSAGE,
  __module__ = 'pyatv.mrp.protobuf.SetHiliteModeMessage_pb2'
  # @@protoc_insertion_point(class_scope:SetHiliteModeMessage)
  ))
_sym_db.RegisterMessage(SetHiliteModeMessage)

setHiliteModeMessage.message_type = _SETHILITEMODEMESSAGE
pyatv_dot_mrp_dot_protobuf_dot_ProtocolMessage__pb2.ProtocolMessage.RegisterExtension(setHiliteModeMessage)

# @@protoc_insertion_point(module_scope)
