# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pyatv/mrp/protobuf/TextInputTraitsMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pyatv/mrp/protobuf/TextInputTraitsMessage.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n/pyatv/mrp/protobuf/TextInputTraitsMessage.proto\"\xe6\x06\n\x0fTextInputTraits\x12G\n\x16\x61utocapitalizationType\x18\x01 \x01(\x0e\x32\'.TextInputTraits.AutocapitalizationType\x12\x33\n\x0ckeyboardType\x18\x02 \x01(\x0e\x32\x1d.TextInputTraits.KeyboardType\x12\x35\n\rreturnKeyType\x18\x03 \x01(\x0e\x32\x1e.TextInputTraits.ReturnKeyType\x12\x16\n\x0e\x61utocorrection\x18\x04 \x01(\x08\x12\x15\n\rspellchecking\x18\x05 \x01(\x08\x12%\n\x1d\x65nablesReturnKeyAutomatically\x18\x06 \x01(\x08\x12\x17\n\x0fsecureTextEntry\x18\x07 \x01(\x08\x12\x1e\n\x16validTextRangeLocation\x18\x08 \x01(\x04\x12\x1c\n\x14validTextRangeLength\x18\t \x01(\x04\x12 \n\x18PINEntrySeparatorIndexes\x18\n \x03(\x04\"L\n\x16\x41utocapitalizationType\x12\x08\n\x04NONE\x10\x00\x12\t\n\x05WORDS\x10\x01\x12\r\n\tSENTENCES\x10\x02\x12\x0e\n\nCHARACTERS\x10\x03\"\xd6\x01\n\x0cKeyboardType\x12\x19\n\x15KEYBOARD_TYPE_DEFAULT\x10\x00\x12\x11\n\rASCII_CAPABLE\x10\x01\x12\x1b\n\x17NUMBERS_AND_PUNCTUATION\x10\x02\x12\x07\n\x03URL\x10\x03\x12\x0e\n\nNUMBER_PAD\x10\x04\x12\r\n\tPHONE_PAD\x10\x05\x12\x12\n\x0eNAME_PHONE_PAD\x10\x06\x12\x11\n\rEMAIL_ADDRESS\x10\x07\x12\x0f\n\x0b\x44\x45\x43IMAL_PAD\x10\x08\x12\x0b\n\x07TWITTER\x10\t\x12\x0e\n\nWEB_SEARCH\x10\n\"\xa7\x01\n\rReturnKeyType\x12\x16\n\x12RETURN_KEY_DEFAULT\x10\x00\x12\x06\n\x02GO\x10\x01\x12\n\n\x06GOOGLE\x10\x02\x12\x08\n\x04JOIN\x10\x03\x12\x08\n\x04NEXT\x10\x04\x12\t\n\x05ROUTE\x10\x05\x12\n\n\x06SEARCH\x10\x06\x12\x08\n\x04SEND\x10\x07\x12\t\n\x05YAHOO\x10\x08\x12\x08\n\x04\x44ONE\x10\t\x12\x12\n\x0e\x45MERGENCY_CALL\x10\n\x12\x0c\n\x08\x43ONTINUE\x10\x0b')
)



_TEXTINPUTTRAITS_AUTOCAPITALIZATIONTYPE = _descriptor.EnumDescriptor(
  name='AutocapitalizationType',
  full_name='TextInputTraits.AutocapitalizationType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WORDS', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SENTENCES', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CHARACTERS', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=459,
  serialized_end=535,
)
_sym_db.RegisterEnumDescriptor(_TEXTINPUTTRAITS_AUTOCAPITALIZATIONTYPE)

_TEXTINPUTTRAITS_KEYBOARDTYPE = _descriptor.EnumDescriptor(
  name='KeyboardType',
  full_name='TextInputTraits.KeyboardType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='KEYBOARD_TYPE_DEFAULT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ASCII_CAPABLE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NUMBERS_AND_PUNCTUATION', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='URL', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NUMBER_PAD', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PHONE_PAD', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NAME_PHONE_PAD', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EMAIL_ADDRESS', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DECIMAL_PAD', index=8, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TWITTER', index=9, number=9,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WEB_SEARCH', index=10, number=10,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=538,
  serialized_end=752,
)
_sym_db.RegisterEnumDescriptor(_TEXTINPUTTRAITS_KEYBOARDTYPE)

_TEXTINPUTTRAITS_RETURNKEYTYPE = _descriptor.EnumDescriptor(
  name='ReturnKeyType',
  full_name='TextInputTraits.ReturnKeyType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RETURN_KEY_DEFAULT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GO', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GOOGLE', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='JOIN', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NEXT', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ROUTE', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SEARCH', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SEND', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='YAHOO', index=8, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DONE', index=9, number=9,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EMERGENCY_CALL', index=10, number=10,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONTINUE', index=11, number=11,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=755,
  serialized_end=922,
)
_sym_db.RegisterEnumDescriptor(_TEXTINPUTTRAITS_RETURNKEYTYPE)


_TEXTINPUTTRAITS = _descriptor.Descriptor(
  name='TextInputTraits',
  full_name='TextInputTraits',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='autocapitalizationType', full_name='TextInputTraits.autocapitalizationType', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='keyboardType', full_name='TextInputTraits.keyboardType', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='returnKeyType', full_name='TextInputTraits.returnKeyType', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='autocorrection', full_name='TextInputTraits.autocorrection', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='spellchecking', full_name='TextInputTraits.spellchecking', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enablesReturnKeyAutomatically', full_name='TextInputTraits.enablesReturnKeyAutomatically', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='secureTextEntry', full_name='TextInputTraits.secureTextEntry', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='validTextRangeLocation', full_name='TextInputTraits.validTextRangeLocation', index=7,
      number=8, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='validTextRangeLength', full_name='TextInputTraits.validTextRangeLength', index=8,
      number=9, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='PINEntrySeparatorIndexes', full_name='TextInputTraits.PINEntrySeparatorIndexes', index=9,
      number=10, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TEXTINPUTTRAITS_AUTOCAPITALIZATIONTYPE,
    _TEXTINPUTTRAITS_KEYBOARDTYPE,
    _TEXTINPUTTRAITS_RETURNKEYTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=922,
)

_TEXTINPUTTRAITS.fields_by_name['autocapitalizationType'].enum_type = _TEXTINPUTTRAITS_AUTOCAPITALIZATIONTYPE
_TEXTINPUTTRAITS.fields_by_name['keyboardType'].enum_type = _TEXTINPUTTRAITS_KEYBOARDTYPE
_TEXTINPUTTRAITS.fields_by_name['returnKeyType'].enum_type = _TEXTINPUTTRAITS_RETURNKEYTYPE
_TEXTINPUTTRAITS_AUTOCAPITALIZATIONTYPE.containing_type = _TEXTINPUTTRAITS
_TEXTINPUTTRAITS_KEYBOARDTYPE.containing_type = _TEXTINPUTTRAITS
_TEXTINPUTTRAITS_RETURNKEYTYPE.containing_type = _TEXTINPUTTRAITS
DESCRIPTOR.message_types_by_name['TextInputTraits'] = _TEXTINPUTTRAITS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TextInputTraits = _reflection.GeneratedProtocolMessageType('TextInputTraits', (_message.Message,), dict(
  DESCRIPTOR = _TEXTINPUTTRAITS,
  __module__ = 'pyatv.mrp.protobuf.TextInputTraitsMessage_pb2'
  # @@protoc_insertion_point(class_scope:TextInputTraits)
  ))
_sym_db.RegisterMessage(TextInputTraits)


# @@protoc_insertion_point(module_scope)
