# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pyatv/mrp/protobuf/TransactionKey.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pyatv/mrp/protobuf/TransactionKey.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\'pyatv/mrp/protobuf/TransactionKey.proto\"6\n\x0eTransactionKey\x12\x12\n\nidentifier\x18\x01 \x01(\t\x12\x10\n\x08userData\x18\x02 \x01(\x0c')
)




_TRANSACTIONKEY = _descriptor.Descriptor(
  name='TransactionKey',
  full_name='TransactionKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='identifier', full_name='TransactionKey.identifier', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='userData', full_name='TransactionKey.userData', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=97,
)

DESCRIPTOR.message_types_by_name['TransactionKey'] = _TRANSACTIONKEY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TransactionKey = _reflection.GeneratedProtocolMessageType('TransactionKey', (_message.Message,), dict(
  DESCRIPTOR = _TRANSACTIONKEY,
  __module__ = 'pyatv.mrp.protobuf.TransactionKey_pb2'
  # @@protoc_insertion_point(class_scope:TransactionKey)
  ))
_sym_db.RegisterMessage(TransactionKey)


# @@protoc_insertion_point(module_scope)
