# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pyatv/mrp/protobuf/TransactionPacket.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import TransactionKey_pb2 as pyatv_dot_mrp_dot_protobuf_dot_TransactionKey__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pyatv/mrp/protobuf/TransactionPacket.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n*pyatv/mrp/protobuf/TransactionPacket.proto\x1a\'pyatv/mrp/protobuf/TransactionKey.proto\"\x8a\x01\n\x11TransactionPacket\x12\x1c\n\x03key\x18\x01 \x01(\x0b\x32\x0f.TransactionKey\x12\x12\n\npacketData\x18\x02 \x01(\x0c\x12\x12\n\nidentifier\x18\x03 \x01(\t\x12\x13\n\x0btotalLength\x18\x04 \x01(\x04\x12\x1a\n\x12totalWritePosition\x18\x05 \x01(\x04')
  ,
  dependencies=[pyatv_dot_mrp_dot_protobuf_dot_TransactionKey__pb2.DESCRIPTOR,])




_TRANSACTIONPACKET = _descriptor.Descriptor(
  name='TransactionPacket',
  full_name='TransactionPacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='TransactionPacket.key', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='packetData', full_name='TransactionPacket.packetData', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='identifier', full_name='TransactionPacket.identifier', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='totalLength', full_name='TransactionPacket.totalLength', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='totalWritePosition', full_name='TransactionPacket.totalWritePosition', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=226,
)

_TRANSACTIONPACKET.fields_by_name['key'].message_type = pyatv_dot_mrp_dot_protobuf_dot_TransactionKey__pb2._TRANSACTIONKEY
DESCRIPTOR.message_types_by_name['TransactionPacket'] = _TRANSACTIONPACKET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TransactionPacket = _reflection.GeneratedProtocolMessageType('TransactionPacket', (_message.Message,), dict(
  DESCRIPTOR = _TRANSACTIONPACKET,
  __module__ = 'pyatv.mrp.protobuf.TransactionPacket_pb2'
  # @@protoc_insertion_point(class_scope:TransactionPacket)
  ))
_sym_db.RegisterMessage(TransactionPacket)


# @@protoc_insertion_point(module_scope)
