#################################################################
## 3D Printer Automations
#################################################################

#################################################################
## Prusa Core One L
#################################################################

        ##########################################################
        ## Prusa Core One L 3D Print Finished
        ##########################################################

- alias: 3D-Printer - Prusa Core One L Print Finished
  id: '3d_printer_prusa_core_one_l_print_finished'

  triggers:
    - trigger: state
      entity_id: sensor.prusa_core_one_l
      from: 'printing'
      to: 'finished'

  conditions:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'
    - condition: not
      conditions:
      - condition: state
        entity_id: sensor.prusa_core_one_l
        state: 'printing'

  actions:
    - action: notify.USER1_devices
      data:
        message: 3D Print Complete (Core One L)
        data:
          tag: prusa_core_one_l
          entity_id: camera.prusa_core_one_l

        ##########################################################
        ## Prusa Core One L Print Stopped
        ##########################################################

- alias: 3D-Printer - Prusa Core One L Print Stopped
  id: '3d_printer_prusa_core_one_l_print_stopped'

  triggers:
    - trigger: state
      entity_id: sensor.prusa_core_one_l
      from: 'printing'
      to: 'stopped'

  conditions:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'
    - condition: not
      conditions:
      - condition: state
        entity_id: sensor.prusa_core_one_l
        state: 'printing'

  actions:
    - action: notify.USER1_devices
      data:
        message: Print Stopped (Core One L)
        data:
          tag: prusa_core_one_l
          entity_id: camera.prusa_core_one_l

        ##########################################################
        ## Prusa Core One L Print Paused
        ##########################################################

- alias: 3D-Printer - Prusa Core One L Print Paused
  id: '3d_printer_prusa_core_one_l_print_paused'

  triggers:
    - trigger: state
      entity_id: sensor.prusa_core_one_l
      from: 'printing'
      to: 'paused'
      for:
        hours: 0
        minutes: 1
        seconds: 0

  conditions:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'
    - condition: not
      conditions:
      - condition: state
        entity_id: sensor.prusa_core_one_l
        state: 'printing'

  actions:
    - action: notify.USER1_devices
      data:
        message: Print Paused (Core One L)
        data:
          tag: prusa_core_one_l
          entity_id: camera.prusa_core_one_l

        ##########################################################
        ## Prusa Core One L Print Error
        ##########################################################

- alias: 3D-Printer - Prusa Core One L Print Error
  id: '3d_printer_prusa_core_one_l_print_error'

  triggers:
    - trigger: state
      entity_id: sensor.prusa_core_one_l
      from: 'printing'
      to: 'error'
      for:
        hours: 0
        minutes: 1
        seconds: 0

  conditions:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'
    - condition: not
      conditions:
      - condition: state
        entity_id: sensor.prusa_core_one_l
        state: 'printing'

  actions:
    - action: notify.USER1_devices
      data:
        message: Print Error (Core One L)
        data:
          tag: prusa_core_one_l
          entity_id: camera.prusa_core_one_l

        ##########################################################
        ## Prusa Core One L Print Attention
        ##########################################################

- alias: 3D-Printer - Prusa Core One L Print Attention
  id: '3d_printer_prusa_core_one_l_print_attention'

  triggers:
    - trigger: state
      entity_id: sensor.prusa_core_one_l
      to: 'attention'
      for:
        hours: 0
        minutes: 1
        seconds: 0

  conditions:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'
    - condition: not
      conditions:
      - condition: state
        entity_id: sensor.prusa_core_one_l
        state: 'printing'

  actions:
    - action: notify.USER1_devices
      data:
        message: Print Needs Attention (Core One L)
        data:
          tag: prusa_core_one_l
          entity_id: camera.prusa_core_one_l

#################################################################
## Prusa Core One
#################################################################

        ##########################################################
        ## Prusa Core One 3D Print Finished
        ##########################################################

- alias: 3D-Printer - Prusa Core One Print Finished
  id: '3d_printer_prusa_core_one_print_finished'

  triggers:
    - trigger: state
      entity_id: sensor.prusa_core_one
      from: 'printing'
      to: 'finished'

  conditions:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'
    - condition: not
      conditions:
      - condition: state
        entity_id: sensor.prusa_core_one
        state: 'printing'

  actions:
    - action: notify.USER1_devices
      data:
        message: 3D Print Complete (Core One)
        data:
          tag: prusa_core_one
          entity_id: camera.prusa_core_one

        ##########################################################
        ## Prusa Core One Print Stopped
        ##########################################################

- alias: 3D-Printer - Prusa Core One Print Stopped
  id: '3d_printer_prusa_core_one_print_stopped'

  triggers:
    - trigger: state
      entity_id: sensor.prusa_core_one
      from: 'printing'
      to: 'stopped'

  conditions:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'
    - condition: not
      conditions:
      - condition: state
        entity_id: sensor.prusa_core_one
        state: 'printing'

  actions:
    - action: notify.USER1_devices
      data:
        message: Print Stopped (Core One)
        data:
          tag: prusa_core_one
          entity_id: camera.prusa_core_one

        ##########################################################
        ## Prusa Core One Print Paused
        ##########################################################

- alias: 3D-Printer - Prusa Core One Print Paused
  id: '3d_printer_prusa_core_one_print_paused'

  triggers:
    - trigger: state
      entity_id: sensor.prusa_core_one
      from: 'printing'
      to: 'paused'
      for:
        hours: 0
        minutes: 1
        seconds: 0

  conditions:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'
    - condition: not
      conditions:
      - condition: state
        entity_id: sensor.prusa_core_one
        state: 'printing'

  actions:
    - action: notify.USER1_devices
      data:
        message: Print Paused (Core One)
        data:
          tag: prusa_core_one
          entity_id: camera.prusa_core_one

        ##########################################################
        ## Prusa Core One Print Error
        ##########################################################

- alias: 3D-Printer - Prusa Core One Print Error
  id: '3d_printer_prusa_core_one_print_error'

  triggers:
    - trigger: state
      entity_id: sensor.prusa_core_one
      from: 'printing'
      to: 'error'
      for:
        hours: 0
        minutes: 1
        seconds: 0

  conditions:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'
    - condition: not
      conditions:
      - condition: state
        entity_id: sensor.prusa_core_one
        state: 'printing'

  actions:
    - action: notify.USER1_devices
      data:
        message: Print Error (Core One)
        data:
          tag: prusa_core_one
          entity_id: camera.prusa_core_one

        ##########################################################
        ## Prusa Core One Print Attention
        ##########################################################

- alias: 3D-Printer - Prusa Core One Print Attention
  id: '3d_printer_prusa_core_one_print_attention'

  triggers:
    - trigger: state
      entity_id: sensor.prusa_core_one
      to: 'attention'
      for:
        hours: 0
        minutes: 1
        seconds: 0

  conditions:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'
    - condition: not
      conditions:
      - condition: state
        entity_id: sensor.prusa_core_one
        state: 'printing'

  actions:
    - action: notify.USER1_devices
      data:
        message: Print Needs Attention (Core One)
        data:
          tag: prusa_core_one
          entity_id: camera.prusa_core_one

#################################################################
## Prusa Core One MMU
#################################################################

        ##########################################################
        ## Prusa Core One MMU 3D Print Finished
        ##########################################################

- alias: 3D-Printer - Prusa Core One MMU Print Finished
  id: '3d_printer_prusa_core_one_mmu_print_finished'

  triggers:
    - trigger: state
      entity_id: sensor.prusa_core_one_mmu
      from: 'printing'
      to: 'finished'

  conditions:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'
    - condition: not
      conditions:
      - condition: state
        entity_id: sensor.prusa_core_one_mmu
        state: 'printing'

  actions:
    - action: notify.USER1_devices
      data:
        message: 3D Print Complete (MMU)
        data:
          tag: prusa_core_one_mmu
          entity_id: camera.prusa_core_one_mmu

        ##########################################################
        ## Prusa Core One MMU Print Stopped
        ##########################################################

- alias: 3D-Printer - Prusa Core One MMU Print Stopped
  id: '3d_printer_prusa_core_one_mmu_print_stopped'

  triggers:
    - trigger: state
      entity_id: sensor.prusa_core_one_mmu
      from: 'printing'
      to: 'stopped'

  conditions:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'
    - condition: not
      conditions:
      - condition: state
        entity_id: sensor.prusa_core_one_mmu
        state: 'printing'

  actions:
    - action: notify.USER1_devices
      data:
        message: Print Stopped (MMU)
        data:
          tag: prusa_core_one_mmu
          entity_id: camera.prusa_core_one_mmu

        ##########################################################
        ## Prusa Core One MMU Print Paused
        ##########################################################

- alias: 3D-Printer - Prusa Core One MMU Print Paused
  id: '3d_printer_prusa_core_one_mmu_print_paused'

  triggers:
    - trigger: state
      entity_id: sensor.prusa_core_one_mmu
      from: 'printing'
      to: 'paused'
      for:
        hours: 0
        minutes: 1
        seconds: 0

  conditions:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'
    - condition: not
      conditions:
      - condition: state
        entity_id: sensor.prusa_core_one_mmu
        state: 'printing'

  actions:
    - action: notify.USER1_devices
      data:
        message: Print Paused (MMU)
        data:
          tag: prusa_core_one_mmu
          entity_id: camera.prusa_core_one_mmu

        ##########################################################
        ## Prusa Core One MMU MMU Print Error
        ##########################################################

- alias: 3D-Printer - Prusa Core One MMU Print Error
  id: '3d_printer_prusa_core_one_mmu_print_error'

  triggers:
    - trigger: numeric_state
      entity_id: sensor.prusa_core_one_mmu_nozzle_temperature
      below: 165
      for:
        hours: 0
        minutes: 1
        seconds: 0

  conditions:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'
    - condition: state
      entity_id: sensor.prusa_core_one_mmu
      state: 'printing'

  actions:
    - action: notify.USER1_devices
      data:
        message: Print Error (MMU)
        data:
          tag: prusa_core_one_mmu
          entity_id: camera.prusa_core_one_mmu

        ##########################################################
        ## Prusa Core One MMU Print Attention
        ##########################################################

- alias: 3D-Printer - Prusa Core One MMU Print Attention
  id: '3d_printer_prusa_core_one_mmu_print_attention'

  triggers:
    - trigger: state
      entity_id: sensor.prusa_core_one_mmu
      to: 'attention'
      for:
        hours: 0
        minutes: 1
        seconds: 0

  conditions:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'
    - condition: not
      conditions:
      - condition: state
        entity_id: sensor.prusa_core_one_mmu
        state: 'printing'

  actions:
    - action: notify.USER1_devices
      data:
        message: Print Needs Attention (MMU)
        data:
          tag: prusa_core_one_mmu
          entity_id: camera.prusa_core_one_mmu