#################################################################
## Bedtime Automations
#################################################################

        ##########################################################
        ## Bedtime
        ##########################################################

- alias: Bedtime - Primary Bedtime
  id: 'bedtime_primary'

  triggers:
    - trigger: state
      entity_id: input_boolean.bedtime
      to: 'on'
      for:
        hours: 0
        minutes: 5
        seconds: 0

  conditions:
    - condition: state
      entity_id: group.household
      state: 'home'

  actions:
    - action: lock.lock
      target:
        entity_id:
        - lock.garage_door
        - lock.patio_door
    - action: switch.turn_off
      data: {}
      target:
        entity_id:
          - switch.living_room_fireplace
          - switch.four_season_room_fireplace
          - switch.primary_bathroom_shower_exhaust_fan
          - switch.primary_bathroom_toilet_exhaust_fan
          - switch.upstairs_bathroom_toilet_exhaust_fan
          - switch.guest_bathroom_exhaust_fan
          - switch.guest_bathroom_toilet_exhaust_fan
          - switch.basement_bathroom_exhaust_fan
          - switch.hallway_bathroom_exhaust_fan
          - switch.media_room_air_purifier
          - switch.USER1s_office_air_purifier
          - switch.basement_storage_air_purifier
          - switch.fountain
          - switch.media_room_ap_led
          - switch.second_floor_ap_led
          - switch.four_season_room_ap_led
    - action: fan.turn_off
      data: {}
      target:
        entity_id:
          - fan.four_season_room_ceiling_fan
          - fan.USER1s_office_ceiling_fan
          - fan.USER2s_office_ceiling_fan
    - action: select.select_option
      data:
        entity_id: select.media_room_activities
        option: "power_off"
    - action: media_player.media_stop
      data: {}
      target:
        entity_id:
          - media_player.USER1_s_office_sonos
          - media_player.bathroom_sonos
          - media_player.bedroom_sonos
          - media_player.dining_room_sonos
          - media_player.four_season_room_sonos
          - media_player.four_season_room_tv_sonos
          - media_player.game_room_sonos
          - media_player.kitchen_sonos
          - media_player.laundry_room_sonos
          - media_player.living_room_sonos
          - media_player.media_room_sonos
          - media_player.media_room_tv_sonos
          - media_player.study_sonos
          - media_player.USER2_s_office_sonos
          - media_player.living_room_tv_sonos
          - media_player.roam_sonos
          - media_player.USER2s_office_tv_sonos
          - media_player.USER1_s_office_tv_sonos
    - action: light.turn_off
      data: {}
      target:
        entity_id:
          - light.living_room_lights
          - light.kitchen_lights
          - light.four_season_room_lights
          - light.laundry_room_main_lights
          - light.dining_room_lights
          - light.hallway_main_lights
          - light.hallway_bathroom_vanity_lights
          - light.study_main_lights
          - light.bedroom_hallway_main_lights
          - light.primary_bedroom_lights
          - light.primary_bathroom_lights
          - light.primary_bedroom_closet
          - light.USER2_s_office_lights
          - light.USER1_s_office_lights
          - light.workshop_ceiling
          - light.upstairs_bathroom_lights
          - light.media_room_lights
          - light.game_room_lights
          - light.basement_bathroom_vanity_lights
          - light.fitness_room_main_lights
          - light.basement_storage_area_main_lights
          - light.stairs_main_lights
          - light.basement_stairs_main_lights
          - light.garage_interior
          - light.guest_bedroom_closet_light
          - light.USER1_s_office_closet_light
          - light.patio_lights
          - light.foyer_chandelier
          - light.USER1_s_office_closet_light
          - light.guest_bedroom_closet_light
    - action: light.turn_on
      target:
        entity_id:
          - light.front_porch
          - light.garage
      data:
        brightness_pct: 15
    - action: climate.set_preset_mode
      data:
        entity_id: 
          - climate.main_floor
          - climate.upstairs
        preset_mode: 'sleep'
    - action: media_player.turn_off
      data: {}
      target:
        entity_id:
          - media_player.four_season_room_apple_tv
          - media_player.media_room_apple_tv
          - media_player.living_room_apple_tv
          - media_player.fitness_room_apple_tv
          - media_player.USER2s_office_apple_tv
          - media_player.USER1s_office_apple_tv
          - media_player.four_season_room_lg_tv
          - media_player.media_room_lg_tv
          - media_player.living_room_lg_tv

        ##########################################################
        ## Bedtime Four Season Room Garage Door
        ##########################################################

- alias: Bedtime - Four Season Room Garage Door
  id: 'bedtime_four_season_room_garage_door'

  triggers:
    - trigger: state
      entity_id: input_boolean.bedtime
      to: 'on'
      for:
        hours: 0
        minutes: 2
        seconds: 0

  conditions:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: cover.four_season_room
      state: 'open'

  actions:
    - action: cover.close_cover
      data: {}
      target:
        entity_id: 
          - cover.four_season_room

        ##########################################################
        ## Bedtime Garage Door
        ##########################################################

- alias: Bedtime - Garage Door
  id: 'bedtime_garage_door'

  triggers:
    - trigger: state
      entity_id: input_boolean.bedtime
      to: 'on'
      for:
        hours: 0
        minutes: 1
        seconds: 0

  conditions:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: cover.garage_door
      state: 'open'

  actions:
    - action: cover.close_cover
      data: {}
      target:
        entity_id: 
          - cover.garage_door

        ##########################################################
        ## Bedtime Workshop Air Purfier
        ##########################################################

- alias: Bedtime - Workshop Air Purifier
  id: 'bedtime_workshop_air_purifier'

  triggers:
    - trigger: state
      entity_id: input_boolean.bedtime
      to: 'on'
      for:
        hours: 0
        minutes: 6
        seconds: 0

  conditions:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: switch.workshop_air_purifier
      state: 'on'
    - condition: not
      conditions:
      - condition: state
        entity_id: sensor.prusa_core_one_l
        state: 'printing'
      - condition: state
        entity_id: sensor.prusa_core_one
        state: 'printing'
      - condition: state
        entity_id: sensor.prusa_core_one_mmu
        state: 'printing'

  actions:
    - action: switch.turn_off
      data: {}
      target:
        entity_id:
          - switch.workshop_air_purifier

        ##########################################################
        ## USER2 Bedtime
        ##########################################################

- alias: Bedtime - USER2
  id: 'bedtime_USER2'

  triggers:
    - trigger: state
      entity_id: input_boolean.USER2_bedtime
      to: 'on'
      for:
        hours: 0
        minutes: 5
        seconds: 0

  conditions:
    - condition: state
      entity_id: person.USER2
      state: 'home'
    - condition: state
      entity_id: input_boolean.bedtime
      state: 'off'
    - condition: or
      conditions:
        - condition: state
          entity_id: input_boolean.guest_mode
          state: 'off'
        - condition: state
          entity_id: input_boolean.patio_party_mode
          state: 'off'

  actions:
    - action: switch.turn_off
      data: {}
      target:
        entity_id:
          - switch.primary_bathroom_shower_exhaust_fan
          - switch.primary_bathroom_toilet_exhaust_fan
          - switch.fountain
    - action: fan.turn_off
      data: {}
      target:
        entity_id:
          - fan.USER2s_office_ceiling_fan
          - fan.primary_bedroom_ceiling_fan
    - action: media_player.media_stop
      data: {}
      target:
        entity_id:
          - media_player.bathroom_sonos
          - media_player.bedroom_sonos
          - media_player.USER2_s_office_sonos
          - media_player.USER2s_office_tv_sonos
    - action: light.turn_off
      data: {}
      target:
        entity_id:
          - light.bedroom_hallway_main_lights
          - light.primary_bedroom_lights
          - light.primary_bathroom_lights
          - light.primary_bedroom_closet
          - light.USER2_s_office_lights
          - light.patio_lights
    - action: climate.set_preset_mode
      data:
        entity_id: 
          - climate.main_floor
        preset_mode: 'sleep'
    - action: media_player.turn_off
      data: {}
      target:
        entity_id:
          - media_player.USER2s_office_apple_tv

        ##########################################################
        ## USER2 Bedtime Guest Mode
        ##########################################################

- alias: Bedtime - USER2 Bedtime Guest Mode
  id: 'bedtime_USER2_guest_mode'

  triggers:
    - trigger: state
      entity_id: input_boolean.USER2_bedtime
      to: 'on'
      for:
        hours: 0
        minutes: 5
        seconds: 0

  conditions:
    - condition: state
      entity_id: person.USER2
      state: 'home'
    - condition: state
      entity_id: input_boolean.bedtime
      state: 'off'
    - condition: or
      conditions:
        - condition: state
          entity_id: input_boolean.guest_mode
          state: 'on'
        - condition: state
          entity_id: input_boolean.patio_party_mode
          state: 'on'

  actions:
    - action: switch.turn_off
      data: {}
      target:
        entity_id:
          - switch.primary_bathroom_shower_exhaust_fan
          - switch.primary_bathroom_toilet_exhaust_fan
    - action: fan.turn_off
      data: {}
      target:
        entity_id:
          - fan.USER2s_office_ceiling_fan
    - action: media_player.media_stop
      data: {}
      target:
        entity_id:
          - media_player.bathroom_sonos
          - media_player.bedroom_sonos
    - action: light.turn_off
      data: {}
      target:
        entity_id:
          - light.bedroom_hallway_main_lights
          - light.primary_bedroom_lights
          - light.primary_bathroom_lights
          - light.primary_bedroom_closet
          - light.USER2_s_office_lights
    - action: climate.set_preset_mode
      data:
        entity_id: 
          - climate.main_floor
        preset_mode: 'sleep'

        ##########################################################
        ## Bedtime USER2 Away
        ##########################################################

- alias: Bedtime - Bedtime USER2 Away
  id: 'bedtime_USER2_away'

  triggers:
    - trigger: state
      entity_id: input_boolean.bedtime
      to: 'on'
      for:
        hours: 0
        minutes: 4
        seconds: 0

  conditions:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: not
      conditions:
        - condition: state
          entity_id: person.USER2
          state: 'home'

  actions:
    - action: fan.turn_on
      data: {}
      target:
        entity_id:
          - fan.primary_bedroom_ceiling_fan
    - delay: '00:00:05'
    - action: fan.set_percentage
      data:
        percentage: 75
      target:
        entity_id: 
          - fan.primary_bedroom_ceiling_fan

        ##########################################################
        ## Bedtime Guest Mode Thermostat
        ##########################################################

- alias: Bedtime - Bedtime Guest Mode Thermostat
  id: 'bedtime_guest_mode_thermostat'

  triggers:
    - trigger: state
      entity_id: input_boolean.bedtime
      to: 'on'
      for:
        hours: 0
        minutes: 7
        seconds: 0

  conditions:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: or
      conditions:
        - condition: state
          entity_id: input_boolean.guest_mode
          state: 'on'
        - condition: state
          entity_id: binary_sensor.guest_bedroom_door_sensor
          state: 'off'

  actions:
    - action: climate.set_preset_mode
      data:
        entity_id: 
          - climate.upstairs
        preset_mode: 'Guest'

        ##########################################################
        ## Bedtime Guest Mode Off
        ##########################################################

- alias: Bedtime - Bedtime Guest Mode Off
  id: 'bedtime_guest_mode_off'

  triggers:
    - trigger: state
      entity_id: input_boolean.bedtime
      to: 'on'
      for:
        hours: 0
        minutes: 6
        seconds: 0

  conditions:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'

  actions:
    - action: light.turn_off
      data: {}
      target:
        entity_id:
          - light.guest_bedroom_lights
          - light.guest_bathroom_lights
    - action: fan.turn_off
      data: {}
      target:
        entity_id:
          - fan.guest_bedroom_ceiling_fan
    - action: media_player.turn_off
      data: {}
      target:
        entity_id:
          - media_player.guest_bedroom_apple_tv
    - action: media_player.media_stop
      data: {}
      target:
        entity_id:
          - media_player.guest_bedroom_tv_sonos

        ##########################################################
        ## Turn AP LEDs When Bedtime Off
        ##########################################################

- alias: Bedtime - Turn AP LEDs On When Bedtime Off
  id: 'bedtime_turn_ap_leds_on_when_bedtime_off'

  triggers:
    - trigger: state
      entity_id: input_boolean.bedtime
      to: 'off'
      for:
        hours: 0
        minutes: 10
        seconds: 0

  conditions:
    - condition: state
      entity_id: group.household
      state: 'home'

  actions:
    - action: switch.turn_on
      data: {}
      target:
        entity_id:
          - switch.media_room_ap_led
          - switch.second_floor_ap_led
          - switch.four_season_room_ap_led

#################################################################
## Helpers
#################################################################

        ##########################################################
        ## Turn on Primary Bedtime if USER1 Not Home
        ##########################################################

- alias: Bedtime - Turn on Primary Bedtime if USER1 Not Home
  id: 'bedtime_primary_if_USER1_not_home'

  triggers:
    - trigger: state
      entity_id: input_boolean.USER2_bedtime
      to: 'on'
      for:
        hours: 0
        minutes: 0
        seconds: 30

  conditions:
    - condition: state
      entity_id: person.USER2
      state: 'home'
    - condition: state
      entity_id: input_boolean.bedtime
      state: 'off'
    - condition: not
      conditions:
        - condition: state
          entity_id: person.USER1
          state: 'home'

  actions:
    - action: homeassistant.turn_on
      data: {}
      target:
        entity_id:
          - input_boolean.bedtime

        ##########################################################
        ## Turn off Bedtime when Bedroom Door Opens
        ##########################################################

- alias: Bedtime - Turn off Bedtime when Bedroom Door Opens
  id: 'bedtime_turn_off_bedtime_when_bedroom_door_opens'

  triggers:
    - trigger: state
      entity_id: binary_sensor.primary_bedroom_door_sensor
      to: 'on'
      for:
        hours: 0
        minutes: 0
        seconds: 0
    - trigger: state
      entity_id: binary_sensor.primary_bedroom_door_sensor
      to: 'on'
      for:
        hours: 0
        minutes: 10
        seconds: 0

  conditions:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: or
      conditions:
        - condition: state
          entity_id: input_boolean.bedtime
          state: 'on'
        - condition: state
          entity_id: input_boolean.USER2_bedtime
          state: 'on'
    - condition: time
      after: '05:00:00'
      before: '19:00:00'

  actions:
    - action: homeassistant.turn_off
      data: {}
      target:
        entity_id:
          - input_boolean.bedtime
          - input_boolean.USER2_bedtime

        ##########################################################
        ## Turn off Bedtime When Bedroom Hallway Motion Detected
        ##########################################################

- alias: Bedtime - Turn off Bedtime When Bedroom Hallway Motion Detected
  id: 'bedtime_turn_off_bedtime_when_bedroom_hallway_motion_detected'

  triggers:
    - trigger: state
      entity_id: binary_sensor.primary_bedroom_hallway_motion_sensor_motion_detection
      to: 'on'
      for:
        hours: 0
        minutes: 0
        seconds: 0

  conditions:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: or
      conditions:
        - condition: state
          entity_id: input_boolean.bedtime
          state: 'on'
        - condition: state
          entity_id: input_boolean.USER2_bedtime
          state: 'on'
    - condition: time
      after: '06:00:00'
      before: '19:00:00'
    - condition: state
      entity_id: binary_sensor.main_floor_cleaning
      state: 'off'

  actions:
    - action: homeassistant.turn_off
      data: {}
      target:
        entity_id:
          - input_boolean.bedtime
          - input_boolean.USER2_bedtime