#################################################################
## Thermostat Automations
#################################################################

        ##########################################################
        ## Set Thermostat Away
        ##########################################################

- alias: Climate - Away
  id: 'climate_away'

  triggers:
    - trigger: state
      entity_id: group.household
      from: 'home'
      to: 'not_home'
      for:
        hours: 0
        minutes: 30
        seconds: 0

  conditions:
    - condition: state
      entity_id: input_boolean.disable_location_automations
      state: 'off'
    - condition: state
      entity_id: input_boolean.disable_climate_automations
      state: 'off'
    - condition: not
      conditions:
      - condition: state
        entity_id: group.household
        state: 'home'
    - condition: numeric_state
      entity_id: sensor.REDACTED_forecasted_temperature_high
      below: 90
    - condition: numeric_state
      entity_id: sensor.REDACTED_forecasted_temperature_low
      above: 15

  actions:
    - action: notify.USER1_devices
      data:
        message: HVAC Shut Off
        data:
          tag: climate
    - action: climate.set_preset_mode
      data:
        entity_id: 
          - climate.main_floor
          - climate.upstairs
        preset_mode: 'away_indefinitely'
    - delay: '00:00:30'
    - action: ecobee.set_fan_min_on_time
      data:
        entity_id: 
          - climate.main_floor
          - climate.upstairs
        fan_min_on_time: '0'

        ##########################################################
        ## Set Thermostat Home
        ##########################################################

- alias: Climate - Home
  id: 'climate_home'

  triggers:
    - trigger: state
      entity_id: group.household
      from: 'not_home'
      to: 'home'
    - trigger: state
      entity_id: input_boolean.out_of_town_mode
      to: 'off'

  conditions:
    - condition: state
      entity_id: input_boolean.disable_location_automations
      state: 'off'
    - condition: state
      entity_id: input_boolean.disable_climate_automations
      state: 'off'

  actions:
    - action: ecobee.resume_program
      data:
        entity_id: 
          - climate.main_floor
          - climate.upstairs
        resume_all: true
    - delay: '00:00:30'
    - action: ecobee.set_fan_min_on_time
      data:
        entity_id: 
          - climate.main_floor
          - climate.upstairs
        fan_min_on_time: '10'

        ##########################################################
        ## Adjust Upstairs Thermostat for Guests
        ##########################################################

- alias: Climate - Adjust Upstairs Thermostat for Guests
  id: 'climate_adjust_upstairs_thermostat_for_guests'

  triggers:
    - trigger: time
      at: '23:32:00'

  conditions:
    - condition: state
      entity_id: input_boolean.disable_climate_automations
      state: 'off'
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: or
      conditions:
        - condition: state
          entity_id: input_boolean.guest_mode
          state: 'on'
        - condition: state
          entity_id: binary_sensor.guest_bedroom_door_sensor
          state: 'off'

  actions:
    - action: climate.set_preset_mode
      data:
        entity_id: climate.upstairs
        preset_mode: 'Guest'

        ##########################################################
        ## Adjust Upstairs Thermostat for Guests after Midnight
        ##########################################################

- alias: Climate - Adjust Upstairs Thermostat for Guests after Midnight
  id: 'climate_adjust_upstairs_thermostat_for_guests_after_midnight'

  triggers:
    - trigger: state
      entity_id: input_boolean.guest_mode
      to: 'on'
    - trigger: state
      entity_id: binary_sensor.guest_bedroom_door_sensor
      to: 'off'
      for:
        hours: 0
        minutes: 30
        seconds: 0

  conditions:
    - condition: time
      after: '00:00:00'
      before: '08:30:00'
    - condition: state
      entity_id: input_boolean.disable_climate_automations
      state: 'off'
    - condition: state
      entity_id: group.household
      state: 'home'

  actions:
    - action: climate.set_preset_mode
      data:
        entity_id: climate.upstairs
        preset_mode: 'Guest'
