#################################################################
## Door Automations
#################################################################

        ##########################################################
        ## Turn On Front Porch & Garage Lights when Front Door Opens
        ##########################################################

- alias: Doors - Turn On Front Porch and Garage Lights when Front Door Opens
  id: 'doors_turn_on_front_porch_garage_lights_when_front_door_opens'

  triggers:
    - trigger: state
      entity_id: binary_sensor.front_door_sensor
      from: 'off'
      to: 'on'

  conditions:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.disable_door_automations
      state: 'off'

  actions:
    - action: light.turn_on
      target:
        entity_id:
          - light.front_porch
          - light.garage
      data:
        brightness_pct: 100
        transition: 1

        ##########################################################
        ## Reset Front Porch Lights Brightness when Front Door Closes
        ##########################################################

- alias: Doors - Reset Front Porch Lights Brightness when Front Door Closes
  id: 'doors_reset_front_porch_lights_brightness_when_front_door_closes'

  triggers:
    - trigger: state
      entity_id: binary_sensor.front_door_sensor
      from: 'on'
      to: 'off'
      for:
        hours: 0
        minutes: 5
        seconds: 0

  conditions:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.disable_door_automations
      state: 'off'
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: time
      after: '14:00:00'
      before: '23:44:00'
    - condition: or
      conditions:
      - condition: state
        entity_id: light.front_porch
        state: 'on'
      - condition: state
        entity_id: light.garage
        state: 'on'
    - condition: state
      entity_id: input_select.exterior_holiday_lighting
      state: 'None'

  actions:
    - action: light.turn_on
      target:
        entity_id:
          - light.front_porch
          - light.garage
      data:
        brightness_pct: 50
        transition: 900

        ##########################################################
        ## Reset Front Porch Lights Brightness when Front Door Closes after Midnight
        ##########################################################

- alias: Doors - Reset Front Porch Lights Brightness when Front Door Closes after Midnight
  id: 'doors_reset_front_porch_lights_brightness_when_front_door_closes_after_midnight'

  triggers:
    - trigger: state
      entity_id: binary_sensor.front_door_sensor
      from: 'on'
      to: 'off'
      for:
        hours: 0
        minutes: 5
        seconds: 0

  conditions:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.disable_door_automations
      state: 'off'
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: time
      after: '00:00:00'
      before: '07:30:00'
    - condition: or
      conditions:
      - condition: state
        entity_id: light.front_porch
        state: 'on'
      - condition: state
        entity_id: light.garage
        state: 'on'

  actions:
    - action: light.turn_on
      target:
        entity_id:
          - light.front_porch
          - light.garage
      data:
        brightness_pct: 15
        transition: 900
    - delay: '00:16:00'
    - action: light.turn_on
      target:
        entity_id:
          - light.front_porch
          - light.garage
      data:
        brightness_pct: 15

        ##########################################################
        ## Turn On Foyer Lights when Front Door Opens
        ##########################################################

- alias: Doors - Turn On Foyer Lights when Front Door Opens
  id: 'doors_turn_on_foyer_lights_when_front_door_opens'

  triggers:
    - trigger: state
      entity_id: binary_sensor.front_door_sensor
      from: 'off'
      to: 'on'

  conditions:
    - condition: or
      conditions:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: sun
        after: sunset
        after_offset: "-00:45:00"
    - condition: state
      entity_id: input_boolean.disable_door_automations
      state: 'off'

  actions:
    - action: light.turn_on
      target:
        entity_id:
          - light.foyer_chandelier
      data:
        brightness_pct: 100
        transition: 1

        ##########################################################
        ## Reset Foyer Lights when Front Door Closes
        ##########################################################

- alias: Doors - Reset Foyer Lights when Front Door Closes
  id: 'doors_reset_foyer_lights_when_front_door_closes'

  triggers:
    - trigger: state
      entity_id: binary_sensor.front_door_sensor
      from: 'on'
      to: 'off'
      for:
        hours: 0
        minutes: 5
        seconds: 0

  conditions:
    - condition: state
      entity_id: input_boolean.disable_door_automations
      state: 'off'
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: light.foyer_chandelier
      state: 'on'
    - condition: or
      conditions:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: sun
        after: sunset
        after_offset: "-00:45:00"

  actions:
    - action: light.turn_on
      target:
        entity_id:
          - light.foyer_chandelier
      data:
        brightness_pct: 25
        transition: 900

        ##########################################################
        ## Turn On Garage Interior Lights when Door Opens
        ##########################################################

- alias: Doors - Turn On Garage Interior Lights when Door Opens
  id: 'doors_turn_on_garage_interior_lights_when_door_opens'

  triggers:
    - trigger: state
      entity_id: binary_sensor.garage_door_sensor
      from: 'off'
      to: 'on'
    - trigger: state
      entity_id: cover.garage_door
      from: 'opening'
      to: 'open'

  conditions:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: input_boolean.disable_door_automations
      state: 'off'

  actions:
    - action: light.turn_on
      target:
        entity_id:
          - light.garage_main_lights
          - light.garage_door
      data:
        brightness_pct: 100

        ##########################################################
        ## Turn Off Garage Interior Lights when Door Closes
        ##########################################################

- alias: Doors - Turn Off Garage Interior Lights when Door Closes
  id: 'doors_turn_off_garage_interior_lights_when_door_closes'

  triggers:
    - trigger: state
      entity_id: binary_sensor.garage_door_sensor
      from: 'on'
      to: 'off'
      for:
        hours: 0
        minutes: 30
        seconds: 0
    - trigger: state
      entity_id: cover.garage_door
      from: 'closing'
      to: 'closed'
      for:
        hours: 0
        minutes: 10
        seconds: 0

  conditions:
    - condition: state
      entity_id: input_boolean.disable_door_automations
      state: 'off'
    - condition: state
      entity_id: binary_sensor.garage_opener_motion
      state: 'off'
    - condition: or
      conditions:
      - condition: state
        entity_id: binary_sensor.garage_door_sensor
        state: 'off'
        for:
          hours: 0
          minutes: 5
          seconds: 0
      - condition: state
        entity_id: cover.garage_door
        state: 'closed'
        for:
          hours: 0
          minutes: 5
          seconds: 0

  actions:
    - action: light.turn_off
      data: {}
      target:
        entity_id:
          - light.garage_main_lights
          - light.garage_door

        ##########################################################
        ## Turn On USER1's Office Closet Light When Door Opens
        ##########################################################

- alias: Doors - Turn On USER1's Office Closet Light When Door Opens
  id: 'doors_turn_on_USER1s_office_closet_light_when_door_opens'

  triggers:
    - trigger: state
      entity_id: binary_sensor.USER1s_office_closet_door_sensor
      from: 'off'
      to: 'on'

  conditions:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: input_boolean.disable_door_automations
      state: 'off'
    - condition: state
      entity_id: light.USER1_s_office_closet_light
      state: 'off'

  actions:
    - action: light.turn_on
      target:
        entity_id:
          - light.USER1_s_office_closet_light
      data:
        brightness_pct: 100

        ##########################################################
        ## Turn Off USER1's Office Closet When Door Closes
        ##########################################################

- alias: Doors - Turn Off USER1's Office Closet When Door Closes
  id: 'doors_turn_off_USER1s_office_closet_when_door_closes'

  triggers:
    - trigger: state
      entity_id: binary_sensor.USER1s_office_closet_door_sensor
      from: 'on'
      to: 'off'

  conditions:
    - condition: state
      entity_id: input_boolean.disable_door_automations
      state: 'off'
    - condition: state
      entity_id: light.USER1_s_office_closet_light
      state: 'on'

  actions:
    - action: light.turn_off
      data: {}
      target:
        entity_id:
          - light.USER1_s_office_closet_light

        ##########################################################
        ## Turn On Workshop Light When Door Opens
        ##########################################################

- alias: Doors - Turn On Workshop Light When Door Opens
  id: 'doors_turn_on_workshop_light_when_door_opens'

  triggers:
    - trigger: state
      entity_id: binary_sensor.workshop_door_sensor
      from: 'off'
      to: 'on'

  conditions:
    - condition: state
      entity_id: person.USER1
      state: 'home'
    - condition: state
      entity_id: input_boolean.disable_door_automations
      state: 'off'
    - condition: state
      entity_id: light.workshop_ceiling
      state: 'off'

  actions:
    - action: light.turn_on
      target:
        entity_id:
          - light.workshop_ceiling
      data:
        brightness_pct: 100

        ##########################################################
        ## Turn On Guest Bedroom Closet Light When Door Opens
        ##########################################################

- alias: Doors - Turn On Guest Bedroom Closet Light When Door Opens
  id: 'doors_turn_on_guest_bedroom_closet_light_when_door_opens'

  triggers:
    - trigger: state
      entity_id: binary_sensor.guest_bedroom_closet_door_sensor
      from: 'off'
      to: 'on'

  conditions:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: input_boolean.disable_door_automations
      state: 'off'
    - condition: state
      entity_id: light.guest_bedroom_closet_light
      state: 'off'

  actions:
    - action: light.turn_on
      target:
        entity_id:
          - light.guest_bedroom_closet_light
      data:
        brightness_pct: 100

        ##########################################################
        ## Turn Off Guest Bedroom Closet When Door Closes
        ##########################################################

- alias: Doors - Turn Off Guest Bedroom Closet Light When Door Closes
  id: 'doors_turn_off_guest_bedroom_closet_light_when_door_closes'

  triggers:
    - trigger: state
      entity_id: binary_sensor.guest_bedroom_closet_door_sensor
      from: 'on'
      to: 'off'

  conditions:
    - condition: state
      entity_id: input_boolean.disable_door_automations
      state: 'off'
    - condition: state
      entity_id: light.guest_bedroom_closet_light
      state: 'on'

  actions:
    - action: light.turn_off
      data: {}
      target:
        entity_id:
          - light.guest_bedroom_closet_light

#################################################################
## Notifications
#################################################################

        ##########################################################
        ## Door Left Open Notification
        ##########################################################

- alias: Doors - Door Left Open Notification
  id: 'doors_left_open_notification'

  mode: parallel
  triggers:
    - trigger: state
      entity_id: 
          - binary_sensor.garage_door_sensor
          - binary_sensor.patio_door_sensor
          - binary_sensor.front_door_sensor
      to: 'on'
      for:
        hours: 0
        minutes: 15
        seconds: 0

  conditions:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  actions:
    - action: notify.USER1_devices
      data:
        message: "{{ trigger.to_state.attributes.friendly_name }} Left Open!"