##################################################################
## Holiday Automations
##################################################################

        ##########################################################
        ## Christmas Tree Bedtime
        ##########################################################

- alias: Holiday - Christmas Tree Bedtime
  id: 'holiday_christmas_tree_bedtime'

  trigger:
    - platform: state
      entity_id: input_boolean.bedtime
      to: 'on'
      for:
        hours: 0
        minutes: 2
        seconds: 0

  condition:
    - condition: state
      entity_id: input_boolean.disable_christmas_automations
      state: 'off'
    - condition: or
      conditions:
      - condition: state
        entity_id: switch.christmas_tree
        state: 'on'
      - condition: state
        entity_id: switch.basement_christmas_tree
        state: 'on'

  action:
    - service: switch.turn_off
      data: {}
      entity_id:
        - switch.christmas_tree
        - switch.basement_christmas_tree

        ##########################################################
        ## Christmas Tree Bedtime Off
        ##########################################################

- alias: Holiday - Christmas Tree Bedtime Off
  id: 'holiday_christmas_tree_bedtime_off'

  trigger:
    - platform: state
      entity_id: input_boolean.bedtime
      to: 'off'
      for:
        hours: 0
        minutes: 0
        seconds: 30

  condition:
    - condition: state
      entity_id: input_boolean.disable_christmas_automations
      state: 'off'
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: or
      conditions:
      - condition: state
        entity_id: switch.christmas_tree
        state: 'off'
      - condition: state
        entity_id: switch.basement_christmas_tree
        state: 'off'

  action:
    - service: switch.turn_on
      data: {}
      entity_id:
        - switch.christmas_tree
        - switch.basement_christmas_tree

        ##########################################################
        ## Christmas Tree Away Mode
        ##########################################################

- alias: Holiday - Tree Away Mode
  id: 'holiday_christmas_tree_away_mode'

  trigger:
    - platform: state
      entity_id: group.household
      from: 'home'
      to: 'not_home'
      for:
        hours: 0
        minutes: 1
        seconds: 0

  condition:
    - condition: state
      entity_id: input_boolean.disable_location_automations
      state: 'off'
    - condition: state
      entity_id: input_boolean.disable_christmas_automations
      state: 'off'
    - condition: or
      conditions:
      - condition: state
        entity_id: switch.christmas_tree
        state: 'on'
      - condition: state
        entity_id: switch.basement_christmas_tree
        state: 'on'

  action:
    - service: switch.turn_off
      data: {}
      entity_id:
        - switch.christmas_tree
        - switch.basement_christmas_tree

        ##########################################################
        ## Christmas Tree Home Mode
        ##########################################################

- alias: Holiday - Christmas Tree Home Mode
  id: 'holiday_christmas_tree_home_mode'

  trigger:
    - platform: state
      entity_id: group.household
      from: 'not_home'
      to: 'home'
      for:
        hours: 0
        minutes: 1
        seconds: 0

  condition:
    - condition: state
      entity_id: input_boolean.disable_location_automations
      state: 'off'
    - condition: state
      entity_id: input_boolean.disable_christmas_automations
      state: 'off'
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: or
      conditions:
      - condition: state
        entity_id: switch.christmas_tree
        state: 'off'
      - condition: state
        entity_id: switch.basement_christmas_tree
        state: 'off'

  action:
    - service: switch.turn_on
      data: {}
      entity_id:
        - switch.christmas_tree
        - switch.basement_christmas_tree

        ##########################################################
        ## Media Room Watching TV Basement Christmas Tree Off
        ##########################################################

- alias: Holiday - Media Room Watching TV Basement Christmas Tree Off
  id: 'holiday_media_room_watching_tv_basement_christmas_tree_off'

  triggers:
    - trigger: state
      entity_id: media_player.media_room_apple_tv
      to: 'playing'
      for:
        hours: 0
        minutes: 0
        seconds: 30

  conditions:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: input_boolean.disable_media_automations
      state: 'off'
    - condition: state
      entity_id: input_boolean.bedtime
      state: 'off'
    - condition: state
      entity_id: input_boolean.disable_christmas_automations
      state: 'off'
    - condition: state
      entity_id: select.media_room_activities
      state: "Watch TV"
    - condition: not
      conditions:
      - condition: state
        entity_id: media_player.media_room_apple_tv
        attribute: app_id
        state: "com.google.ios.youtube"
    - condition: not
      conditions:
      - condition: state
        entity_id: media_player.media_room_apple_tv
        attribute: app_name
        state: "YouTube"
    - condition: not
      conditions:
      - condition: state
        entity_id: media_player.media_room_apple_tv
        attribute: app_id
        state: "com.apple.TVPhotos"
    - condition: state
      entity_id: switch.basement_christmas_tree
      state: 'on'

  action:
    - service: switch.turn_off
      data: {}
      entity_id:
        - switch.basement_christmas_tree

        ##########################################################
        ## Media Room Watching TV Basement Christmas Tree On
        ##########################################################

- alias: Holiday - Media Room Watching TV Basement Christmas Tree On
  id: 'holiday_media_room_watching_tv_basement_christmas_tree_on'

  triggers:
    - trigger: state
      entity_id: media_player.media_room_apple_tv
      to: 'paused'
      for:
        hours: 0
        minutes: 0
        seconds: 15
    - trigger: state
      entity_id: media_player.media_room_apple_tv
      to: 'idle'
      for:
        hours: 0
        minutes: 0
        seconds: 15

  conditions:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: input_boolean.disable_media_automations
      state: 'off'
    - condition: state
      entity_id: input_boolean.disable_christmas_automations
      state: 'off'
    - condition: state
      entity_id: select.media_room_activities
      state: "Watch TV"
    - condition: state
      entity_id: input_boolean.bedtime
      state: 'off'
    - condition: state
      entity_id: switch.basement_christmas_tree
      state: 'off'

  action:
    - service: switch.turn_on
      data: {}
      entity_id:
        - switch.basement_christmas_tree

        ##########################################################
        ## Christmas Lighting
        ##########################################################

- alias: Holiday - Christmas Lighting On at Sunset
  id: 'holiday_christmas_lighting_on_at_sunset'

  triggers:
    - trigger: sun
      event: 'sunset'
      offset: '-00:15:00'

  conditions:
    - condition: state
      entity_id: input_boolean.disable_exterior_light_automations
      state: 'off'
    - condition: state
      entity_id: input_select.exterior_holiday_lighting
      state: 'Christmas'

  actions:
    - action: light.turn_on
      entity_id: 
        - light.front_porch_right
        - light.garage_right
      data:
        transition: 900
        brightness_pct: 100
        rgb_color: [0,255,0]
    - action: light.turn_on
      entity_id: 
        - light.front_porch_left
        - light.garage_left
      data:
        transition: 900
        brightness_pct: 100
        rgb_color: [255,0,0]

        ##########################################################
        ## Christmas Lighting Rotate Colors
        ##########################################################

- alias: Holiday - Christmas Lighting Rotate Colors
  id: 'holiday_christmas_lighting_rotate_colors'

  triggers:
    trigger: time_pattern
    minutes: /5

  conditions:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_select.exterior_holiday_lighting
      state: 'Christmas'
    - condition: or
      conditions:
      - condition: state
        entity_id: light.front_porch
        state: 'on'
        for:
          hours: 0
          minutes: 15
          seconds: 0
      - condition: state
        entity_id: light.garage
        state: 'on'
        for:
          hours: 0
          minutes: 15
          seconds: 0

  actions:
    - action: light.turn_on
      entity_id: 
        - light.front_porch_right
        - light.garage_right
      data:
        transition: 15
        rgb_color: '{{ states(''input_select.exterior_christmas_light_color_right'') }}'
    - action: light.turn_on
      entity_id: 
        - light.front_porch_left
        - light.garage_left
      data:
        transition: 15
        rgb_color: '{{ states(''input_select.exterior_christmas_light_color_left'') }}'
    - action: input_select.select_option
      target:
        entity_id: input_select.exterior_christmas_light_color_right
      data:
        option: >
          {{ state_attr('input_select.exterior_christmas_light_color_right', 'options')
              | reject('eq', states('input_select.exterior_christmas_light_color_right'))
              | list | random }}
    - action: input_select.select_option
      target:
        entity_id: input_select.exterior_christmas_light_color_left
      data:
        option: >
          {{ state_attr('input_select.exterior_christmas_light_color_left', 'options')
              | reject('eq', states('input_select.exterior_christmas_light_color_left'))
              | list | random }}

        ##########################################################
        ## Halloween Lighting On at Sunset
        ##########################################################

- alias: Holiday - Halloween Lighting On at Sunset
  id: 'holiday_halloween_lighting_on_at_sunset'

  triggers:
    - trigger: sun
      event: 'sunset'
      offset: '-00:15:00'

  conditions:
    - condition: state
      entity_id: input_boolean.disable_exterior_light_automations
      state: 'off'
    - condition: state
      entity_id: input_select.exterior_holiday_lighting
      state: 'Halloween'

  actions:
    - action: light.turn_on
      entity_id: 
        - light.front_porch_right
        - light.garage_right
      data:
        transition: 900
        brightness_pct: 100
        rgb_color: [160,6,255]
    - action: light.turn_on
      entity_id: 
        - light.front_porch_left
        - light.garage_left
      data:
        transition: 900
        brightness_pct: 100
        rgb_color: [255,85,7]

        ##########################################################
        ## Halloween Lighting Rotate Colors
        ##########################################################

- alias: Holiday - Halloween Lighting Rotate Colors
  id: 'holiday_halloween_lighting_rotate_colors'

  triggers:
    trigger: time_pattern
    minutes: /5

  conditions:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_select.exterior_holiday_lighting
      state: 'Halloween'
    - condition: or
      conditions:
      - condition: state
        entity_id: light.front_porch
        state: 'on'
        for:
          hours: 0
          minutes: 15
          seconds: 0
      - condition: state
        entity_id: light.garage
        state: 'on'
        for:
          hours: 0
          minutes: 15
          seconds: 0

  actions:
    - action: light.turn_on
      entity_id: 
        - light.front_porch_right
        - light.garage_right
      data:
        transition: 15
        rgb_color: '{{ states(''input_select.exterior_halloween_light_color_right'') }}'
    - action: light.turn_on
      entity_id: 
        - light.front_porch_left
        - light.garage_left
      data:
        transition: 15
        rgb_color: '{{ states(''input_select.exterior_halloween_light_color_left'') }}'
    - action: input_select.select_option
      target:
        entity_id: input_select.exterior_halloween_light_color_right
      data:
        option: >
          {{ state_attr('input_select.exterior_halloween_light_color_right', 'options')
              | reject('eq', states('input_select.exterior_halloween_light_color_right'))
              | list | random }}
    - action: input_select.select_option
      target:
        entity_id: input_select.exterior_halloween_light_color_left
      data:
        option: >
          {{ state_attr('input_select.exterior_halloween_light_color_left', 'options')
              | reject('eq', states('input_select.exterior_halloween_light_color_left'))
              | list | random }}