#################################################################
## iOS Action Automations
#################################################################

        #################################################################
        ## Bedtime
        #################################################################

- alias: iOS Action - Bedtime
  id: 'ios_action_bedtime'

  triggers:
    - trigger: event
      event_type: ios.action_fired
      event_data:
        actionName: 'Bedtime'

  actions:
    - action: homeassistant.turn_on
      target:
        entity_id:
          - input_boolean.bedtime

        #################################################################
        ## Arm Alarm Home
        #################################################################

- alias: iOS Action - Arm Alarm Home
  id: 'ios_action_arm_alarm_home'

  triggers:
    - trigger: event
      event_type: ios.action_fired
      event_data:
        actionName: 'Arm Alarm Home'

  actions:
    - action: alarm_control_panel.alarm_arm_home
      entity_id: alarm_control_panel.alarm

        #################################################################
        ## Arm Alarm Away
        #################################################################

- alias: iOS Action - Arm Alarm Away
  id: 'ios_action_arm_alarm_away'

  triggers:
    - trigger: event
      event_type: ios.action_fired
      event_data:
        actionName: 'Arm Alarm Away'

  actions:
    - action: alarm_control_panel.alarm_arm_away
      entity_id: alarm_control_panel.alarm

        #################################################################
        ## Disarm Alarm
        #################################################################

- alias: iOS Action - Disarm Alarm
  id: 'ios_action_disarm_alarm'

  triggers:
    - trigger: event
      event_type: ios.action_fired
      event_data:
        actionName: 'Disarm Alarm'

  actions:
    - action: alarm_control_panel.alarm_disarm
      entity_id: alarm_control_panel.alarm

        #################################################################
        ## Toggle Garage Door
        #################################################################

- alias: iOS Action - Toggle Garage Door
  id: 'ios_action_automation_toogle_garage_door'

  triggers:
    - trigger: event
      event_type: ios.action_fired
      event_data:
        actionName: 'Toggle Garage Door'

  actions:
    - action: cover.toggle
      target:
        entity_id: cover.garage_door
      data: {}

        #################################################################
        ## Unlock Garage Door
        #################################################################

- alias: iOS Action - Unlock Garage Door
  id: 'ios_action_automation_unlock_garage_door'

  triggers:
    - trigger: event
      event_type: ios.action_fired
      event_data:
        actionName: 'Unlock Garage Door'

  actions:
    - action: lock.unlock
      target:
        entity_id: lock.garage_door
      data: {}

        #################################################################
        ## Unlock Patio Door
        #################################################################

- alias: iOS Action - Unlock Patio Door
  id: 'ios_action_automation_unlock_patio_door'

  triggers:
    - trigger: event
      event_type: ios.action_fired
      event_data:
        actionName: 'Unlock Patio Door'

  actions:
    - action: lock.unlock
      target:
        entity_id: lock.patio_door
      data: {}

        #################################################################
        ## Lock Doors
        #################################################################

- alias: iOS Action - Lock Doors
  id: 'ios_action_automation_lock_doors'

  triggers:
    - trigger: event
      event_type: ios.action_fired
      event_data:
        actionName: 'Lock Doors'

  actions:
    - action: lock.lock
      target:
        entity_id: 
          - lock.garage_door
          - lock.patio_door
      data: {}

#################################################################
## iOS Actionable Notifications
#################################################################

        #################################################################
        ## Close Garage
        #################################################################

- alias: iOS Action - Close Garage
  id: 'ios_action_close_garage'

  triggers:
    - trigger: event
      event_type: mobile_app_notification_action
      event_data:
        action: "close_garage"

  actions:
    - action: cover.close_cover
      entity_id: cover.garage_door

        #################################################################
        ## Open Garage
        #################################################################

- alias: iOS Action - Open Garage
  id: 'ios_action_open_garage'

  triggers:
    - trigger: event
      event_type: mobile_app_notification_action
      event_data:
        action: "open_garage"

  actions:
    - action: cover.open_cover
      entity_id: cover.garage_door

        #################################################################
        ## Disarm Alarm
        #################################################################

- alias: iOS Action - Silence Alarm
  id: 'ios_action_silence_alarm'

  triggers:
    - trigger: event
      event_type: mobile_app_notification_action
      event_data:
        action: "disarm_alarm"

  actions:
    - action: alarm_control_panel.alarm_disarm
      entity_id: alarm_control_panel.alarm

        #################################################################
        ## Enable Alarm
        #################################################################

- alias: iOS Action - Enable Alarm
  id: 'ios_action_enable_alarm'

  triggers:
    - trigger: event
      event_type: mobile_app_notification_action
      event_data:
        action: "arm_alarm"

  actions:
    - action: alarm_control_panel.alarm_arm_away
      entity_id: alarm_control_panel.alarm

        #################################################################
        ## Siren Off
        #################################################################

- alias: iOS Action - Siren
  id: 'ios_action_siren'

  triggers:
    - trigger: event
      event_type: mobile_app_notification_action
      event_data:
        action: "siren_off"

  actions:
    - action: siren.turn_off
      entity_id: siren.siren
