#################################################################
## Door Lock Automations
#################################################################

        ##########################################################
        ## Lock Doors at 2a
        ##########################################################

- alias: Locks - Lock Doors at 2a
  id: 'locks_lock_back_door_at_2a'

  triggers:
    - trigger: time
      at: '02:00:00'

  conditions:
    - condition: state
      entity_id: input_boolean.disable_door_lock_automations
      state: 'off'
    #- condition: state
    #  entity_id: binary_sensor.doors
    #  state: 'off'

  actions:
    - action: lock.lock
      data: {}
      target:
        entity_id:
          - lock.garage_door
          - lock.patio_door

#################################################################
## Notifications
#################################################################

        ##########################################################
        ## Locks Low Battery Notification
        ##########################################################

- alias: Locks - Low Battery Notification
  id: 'locks_low_battery_notification'

  mode: parallel
  triggers:
    - trigger: numeric_state
      entity_id: 
          - sensor.garage_door_lock_battery_level
          - sensor.kitchen_door_lock_battery_level
          - sensor.patio_door_lock_battery_level
      below: 30
      for:
        hours: 1
        minutes: 0
        seconds: 0

  conditions:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  actions:
    - action: notify.USER1_devices
      data:
        message: "{{ trigger.to_state.attributes.friendly_name }} Low"