#################################################################
## System
#################################################################

        ##########################################################
        ## Reset Overrides at 7a
        ##########################################################

- alias: System - Reset Overrides at 7a
  id: 'system_reset_overrides_at_7a'

  triggers:
   - trigger: time
     at: '07:00:00'

  conditions:
    - condition: state
      entity_id: input_boolean.out_of_town_mode
      state: 'off'

  actions:
    - action: homeassistant.turn_off
      data: {}
      target:
        entity_id:
          - input_boolean.disable_camera_automations
          - input_boolean.disable_climate_automations
          - input_boolean.disable_door_automations
          - input_boolean.disable_door_lock_automations
          - input_boolean.disable_exhaust_fan_automations
          - input_boolean.disable_exterior_light_automations
          - input_boolean.disable_fan_automations
          - input_boolean.disable_garage_automations
          - input_boolean.disable_interior_light_automations
          - input_boolean.disable_location_automations
          - input_boolean.disable_media_automations
          - input_boolean.disable_motion_automations
          - input_boolean.disable_notifications
          - input_boolean.disable_vacuum_automations
          - input_boolean.disable_water_works_automations
          - input_boolean.patio_party_mode
    - action: switch.turn_on
      target:
        entity_id:
          - switch.ad_block

        #################################################################
        ## Clear Erroneous Failed Login Notifications
        #################################################################

- alias: System - Clear Erroneous Failed Login Notifications
  id: 'system_clear_erroneous_failed_login_notifications'

  triggers:
    - trigger: state
      entity_id: persistent_notification.http_login
      to: 'notifying'

  actions:
    - delay: "00:00:01"
    - action: persistent_notification.dismiss
      data:
        notification_id: http-login

        #################################################################
        ## Ping Locks if they become Unavailable
        #################################################################

- alias: System - Ping Locks if they become Unavailable
  id: 'system_ping_locks_if_they_become_unavailable'

  triggers:
    - trigger: state
      entity_id: lock.garage_door
      to: 'unavailable'
      for:
        hours: 0
        minutes: 5
        seconds: 0
    - trigger: state
      entity_id: lock.patio_door
      to: 'unavailable'
      for:
        hours: 0
        minutes: 5
        seconds: 0
    - trigger: state
      entity_id: lock.kitchen_door
      to: 'unavailable'
      for:
        hours: 0
        minutes: 5
        seconds: 0
    - trigger: state
      entity_id: lock.garage_door
      to: 'unavailable'
      for:
        hours: 0
        minutes: 10
        seconds: 0
    - trigger: state
      entity_id: lock.patio_door
      to: 'unavailable'
      for:
        hours: 0
        minutes: 10
        seconds: 0
    - trigger: state
      entity_id: lock.kitchen_door
      to: 'unavailable'
      for:
        hours: 0
        minutes: 10
        seconds: 0
    - trigger: state
      entity_id: lock.garage_door
      to: 'unknown'
      for:
        hours: 0
        minutes: 5
        seconds: 0
    - trigger: state
      entity_id: lock.patio_door
      to: 'unknown'
      for:
        hours: 0
        minutes: 5
        seconds: 0
    - trigger: state
      entity_id: lock.kitchen_door
      to: 'unknown'
      for:
        hours: 0
        minutes: 5
        seconds: 0
    - trigger: state
      entity_id: lock.garage_door
      to: 'unknown'
      for:
        hours: 0
        minutes: 10
        seconds: 0
    - trigger: state
      entity_id: lock.patio_door
      to: 'unknown'
      for:
        hours: 0
        minutes: 10
        seconds: 0
    - trigger: state
      entity_id: lock.kitchen_door
      to: 'unknown'
      for:
        hours: 0
        minutes: 10
        seconds: 0

  actions:
    - action: zwave_js.ping
      data: {}
      target:
        entity_id: 
          - lock.garage_door
          - lock.patio_door
          - lock.kitchen_door

        #################################################################
        ## Turn On USER1 Office Do not Disturb when MacBook AV Input On
        #################################################################

- alias: System - Turn On USER1 Office Do not Disturb when MacBook AV Input On
  id: 'system_turn_on_USER1_office_do_not_disturb_when_macbook_av_input_on'

  triggers:
    - trigger: state
      entity_id: binary_sensor.USER1s_macbook_pro_camera_in_use
      to: 'on'
      for:
        hours: 0
        minutes: 1
        seconds: 0
    - trigger: state
      entity_id: binary_sensor.USER1s_macbook_pro_audio_input_in_use
      to: 'on'
      for:
        hours: 0
        minutes: 1
        seconds: 0
#    - trigger: state
#      entity_id: binary_sensor.USER1_s_macbook_pro_focus
#      to: 'on'
#      for:
#        hours: 0
#        minutes: 1
#        seconds: 0
    - trigger: state
      entity_id: sensor.USER1s_macbook_pro_active_audio_input
      from: 'Inactive'
      for:
        hours: 0
        minutes: 1
        seconds: 0

  conditions:
    - condition: state
      entity_id: person.USER1
      state: 'home'
    - condition: state
      entity_id: binary_sensor.USER1s_macbook_pro_active
      state: 'on'
    - condition: state
      entity_id: input_boolean.USER1_s_office_do_not_disturb
      state: 'off'

  actions:
    - action: homeassistant.turn_on
      data: {}
      target:
        entity_id: 
          - input_boolean.USER1_s_office_do_not_disturb

        #################################################################
        ## Turn Off USER1 Office Do not Disturb when MacBook AV Input Off
        #################################################################

- alias: System - Turn Off USER1 Office Do not Disturb when MacBook AV Input Off
  id: 'system_turn_off_USER1_office_do_not_disturb_when_macbook_av_input_off'

  triggers:
    - trigger: state
      entity_id: binary_sensor.USER1s_macbook_pro_camera_in_use
      to: 'off'
      for:
        hours: 0
        minutes: 5
        seconds: 0
    - trigger: state
      entity_id: binary_sensor.USER1s_macbook_pro_audio_input_in_use
      to: 'off'
      for:
        hours: 0
        minutes: 5
        seconds: 0
    - trigger: state
      entity_id: binary_sensor.USER1s_macbook_pro_focus
      to: 'off'
      for:
        hours: 0
        minutes: 5
        seconds: 0
    - trigger: state
      entity_id: sensor.USER1s_macbook_pro_active_audio_input
      to: 'Inactive'
      for:
        hours: 0
        minutes: 5
        seconds: 0

  conditions:
    - condition: state
      entity_id: person.USER1
      state: 'home'
    - condition: state
      entity_id: input_boolean.USER1_s_office_do_not_disturb
      state: 'on'
    - condition: state
      entity_id: binary_sensor.USER1s_macbook_pro_camera_in_use
      state: 'off'
    - condition: state
      entity_id: binary_sensor.USER1s_macbook_pro_audio_input_in_use
      state: 'off'
#    - condition: state
#      entity_id: binary_sensor.USER1s_macbook_pro_focus
#      state: 'off'

  actions:
    - action: homeassistant.turn_off
      data: {}
      target:
        entity_id: 
          - input_boolean.USER1_s_office_do_not_disturb

#################################################################
## Work Arounds
#################################################################

        ##########################################################
        ## Turn On Smart Switch if Turned Off
        ##########################################################

- alias: System - Turn On Smart Switch if Turned Off
  id: 'system_turn_on_smart_switch_if_turned_off'
  
  mode: parallel
  triggers:
    - trigger: state
      entity_id:
        - switch.front_yard_front_porch_light
        - switch.front_yard_garage_sconces
        - switch.USER1_s_office_ceiling_fan
      to: 'off'
      for:
        hours: 0
        minutes: 0
        seconds: 5

  actions:
    - action: switch.turn_on
      data: {}
      target:
        entity_id: "{{ trigger.entity_id }}"

        ##########################################################
        ## Reload USER1's Office Apple TV
        ##########################################################

- alias: System - Reload USER1's Office Apple TV
  id: 'system_reload_USER1s_office_apple_tv'

  triggers:
   - trigger: time
     at: '06:00:00'
   - trigger: time
     at: '12:00:00'
   - trigger: time
     at: '06:00:00'
   - trigger: time
     at: '02:00:00'

  actions:
    - action: homeassistant.reload_config_entry
      target: {}
      data:
        entry_id: 01K58C2JY66WSBQ5QKBV6RRKPW

#################################################################
## Servers
#################################################################

        ##########################################################
        ## Shutdown Windows VM at Bedtime
        ##########################################################

- alias: System Shutdown Windows VM at Bedtime
  id: 'system_shutdown_windows_vm_at_bedtime'

  triggers:
    - trigger: state
      entity_id: input_boolean.bedtime
      to: 'on'
      for:
        hours: 0
        minutes: 5
        seconds: 0

  conditions:
    - condition: state
      entity_id: binary_sensor.qemu_windows_100_status
      state: 'on'

  actions:
    - action: button.press
      target:
        entity_id: button.qemu_windows_100_shutdown

        ##########################################################
        ## Shutdown Windows VM when Household Away
        ##########################################################

- alias: System - Shutdown Windows VM when Household Away
  id: 'system_shutdown_windows_vm_when_household_away'

  triggers:
    - trigger: state
      entity_id: group.household
      from: 'home'
      to: 'not_home'
      for:
        hours: 0
        minutes: 30
        seconds: 0

  conditions:
    - condition: state
      entity_id: binary_sensor.qemu_windows_100_status
      state: 'on'

  actions:
    - action: button.press
      target:
        entity_id: button.qemu_windows_100_shutdown

#################################################################
## Network
#################################################################

        ##########################################################
        ## Re-Enable Pi-hole After 15 Mins
        ##########################################################

- alias: System - Re-Enable Pi-hole After 15 Mins
  id: 'system_reenable_pihole_after_15_mins'

  triggers:
    - trigger: state
      entity_id: switch.ad_block
      from: 'on'
      to: 'off'
      for:
        hours: 0
        minutes: 15
        seconds: 0

  conditions:
    - condition: state
      entity_id: switch.ad_block
      state: 'off'

  actions:
    - action: switch.turn_on
      target:
        entity_id:
          - switch.ad_block

#################################################################
## Notifications
#################################################################

        #################################################################
        ## Home Assistant Started iOS Notification
        #################################################################

- alias: System - Home Assistant Start iOS Notification
  id: 'system_home_assistant_start_ios_notification'

  triggers:
    - trigger: homeassistant
      event: start

  conditions:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  actions:
    - action: notify.USER1_devices
      data:
        message: Home Assistant Started
        data:
          tag: homeassistant

        #################################################################
        ## Home Assistant Update iOS Notification
        #################################################################

- alias: System - Home Assistant Update iOS Notification
  id: 'system_home_assistant_update_ios_notification'

  triggers:
    - trigger: state
      entity_id: binary_sensor.docker_hub_update_available
      to: 'on'
      for:
        hours: 0
        minutes: 5
        seconds: 0

  conditions:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  actions:
    - action: notify.USER1_devices
      data:
        message: Update Available for Home Assistant
        data:
          tag: homeassistant