#################################################################
## Home Assistant Core
#################################################################

homeassistant:
  auth_providers:
    - type: homeassistant
    #- type: trusted_networks
    #  trusted_networks:
    #    - REDACTED.0/24
  customize: !include customize.yaml
default_config:
http:
  use_x_forREDACTEDed_for: true
  trusted_proxies:
    - REDACTED09.3
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  ip_ban_enabled: false
go2rtc:
  debug_ui: false
#  login_attempts_threshold: 10
#logger:
#  default: warning
#  logs:
#    homeassistant.components.zha: debug

#################################################################
## Components
#################################################################

alarm_control_panel:
  - platform: manual
    name: Alarm
    unique_id: REDACTED_alarm_panel
    code_arm_required: false
    arming_time: 30
    delay_time: 30
    trigger_time: 120
    disarmed:
      trigger_time: 0
    armed_home:
      arming_time: 30
      delay_time: 30
      trigger_time: 120
    armed_night:
      arming_time: 30
      delay_time: 30
      trigger_time: 120 
    armed_vacation:
      arming_time: 30
      delay_time: 15
      trigger_time: 120 
    armed_away:
      arming_time: 30
      delay_time: 15
      trigger_time: 120

route53:
  aws_access_key_id: !secret aws_access_key_id_route53
  aws_secret_access_key: !secret aws_secret_access_key_route53
  zone: !secret aws_zone_route53
  domain: !secret aws_domain_route53
  records:
    - home

rest_command:
  pihole_login:
    url: '{{ api_url }}/auth'
    method: POST
    payload: '{ "password" : "{{ password }}" }'
    content_type:  'application/json; charset=utf-8'
    verify_ssl: false
  pihole_logout:
    url: '{{ api_url }}/auth'
    method: DELETE
    verify_ssl: false
    headers:
      sid: "{{ sid }}"
  pihole_set_blocking:
    url: '{{ api_url }}/dns/blocking'
    method: POST
    payload: '{ "blocking" : {{ blocking }}, "timer" : {{ timer }} }'
    content_type:  'application/json; charset=utf-8'
    verify_ssl: false
    headers:
      sid: "{{ sid }}"

#################################################################
## Notifications
#################################################################

notify:
  - platform: group
    name: REDACTED_devices
    services:
      - service: mobile_app_REDACTEDs_iphone
      - service: mobile_app_REDACTED_s_ipad
      - service: mobile_app_REDACTEDs_macbook_pro

  - platform: group
    name: USER2_devices
    services:
      - service: mobile_app_USER2_s_iphone
      - service: mobile_app_USER2_s_ipad

#################################################################
## Includes
#################################################################

automation manual: !include_dir_merge_list automation/
automation ui: !include automations.yaml
group: !include groups.yaml
script: !include scripts.yaml
homekit: !include homekit.yaml
emulated_hue: !include emulated_hue.yaml
template: !include template.yaml
#command_line: !include command_line.yaml
python_script:
ios: !include ios.yaml