#################################################################
## Bedtime Automations
#################################################################

        ##########################################################
        ## Bedtime
        ##########################################################

- alias: Bedtime

  trigger:
    - platform: state
      entity_id: input_boolean.bedtime
      to: 'on'
      for:
        hours: 0
        minutes: 5
        seconds: 0

  condition:
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'

  action:
    - service: lock.lock
      entity_id: group.all_locks
    - service: light.turn_off
      entity_id:
        - group.interior_lights
        - light.globe
        - light.backyard_deck
    - service: switch.turn_off
      entity_id:
        - switch.air_purifier
        - switch.office_fan
        - switch.lower_backyard_lighting
        - switch.backyard_patio_lighting
        - switch.fireplace
    - service: cover.close_cover
      entity_id: cover.garage_door
    - service: homeassistant.turn_off
      entity_id:
        - input_boolean.interior_holiday
        - input_boolean.office_rainbow
        - input_boolean.livingroom_rainbow
        - input_boolean.front_porch_rainbow
        - input_boolean.pop_music
        - input_boolean.jazz_music
        - input_boolean.chill_music
        - input_boolean.electronic_music
        - input_boolean.classical_music
        - input_boolean.adele_music
        - input_boolean.group_all_sonos
    - service: input_select.select_option
      data:
        entity_id: input_select.remote
        option: "PowerOff"
    - service: input_select.select_option
      data:
        entity_id: input_select.sonos
        option: "None"
    - service: media_player.media_stop
      entity_id:
        - media_player.sonos_media_center
        - media_player.sonos_living_room
        - media_player.sonos_dining_room
        - media_player.sonos_kitchen
        - media_player.sonos_bathroom
        - media_player.sonos_bedroom
        - media_player.sonos_USER1s_office
        - media_player.sonos_USER2s_office
        - media_player.sonos_basement
        - media_player.sonos_backyard_patio
    - service: climate.set_operation_mode
      data:
        entity_id: climate.window_unit
        operation_mode: 'off'

        ##########################################################
        ## Bedtime Guest Mode
        ##########################################################

- alias: Bedtime - Guest Mode

  trigger:
    - platform: state
      entity_id: input_boolean.bedtime
      to: 'on'
      for:
        hours: 0
        minutes: 5
        seconds: 0

  condition:
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'on'

  action:
    - service: lock.lock
      entity_id: group.all_locks
    - service: light.turn_off
      entity_id:
        - group.interior_lights
        - light.globe
        - light.backyard_deck
    - service: switch.turn_off
      entity_id:
        - switch.air_purifier
        - switch.lower_backyard_lighting
        - switch.backyard_patio_lighting
        - switch.fireplace
        - switch.office_fan
    - service: cover.close_cover
      entity_id: cover.garage_door
    - service: homeassistant.turn_off
      entity_id:
        - input_boolean.interior_holiday
        - input_boolean.office_rainbow
        - input_boolean.livingroom_rainbow
        - input_boolean.front_porch_rainbow
        - input_boolean.pop_music
        - input_boolean.jazz_music
        - input_boolean.chill_music
        - input_boolean.electronic_music
        - input_boolean.classical_music
        - input_boolean.adele_music
        - input_boolean.group_all_sonos
    - service: input_select.select_option
      data:
        entity_id: input_select.remote
        option: "PowerOff"
    - service: input_select.select_option
      data:
        entity_id: input_select.office_remote
        option: "PowerOff"
    - service: input_select.select_option
      data:
        entity_id: input_select.sonos
        option: "None"
    - service: media_player.media_stop
      entity_id:
        - media_player.sonos_media_center
        - media_player.sonos_living_room
        - media_player.sonos_dining_room
        - media_player.sonos_kitchen
        - media_player.sonos_bathroom
        - media_player.sonos_bedroom
        - media_player.sonos_USER1s_office
        - media_player.sonos_USER2s_office
        - media_player.sonos_basement
        - media_player.sonos_backyard_patio
    - service: climate.set_hold_mode
      data:
        entity_id: climate.main_floor
        hold_mode: "smart3"

        ##########################################################
        ## Bedtime Before 11:30p
        ##########################################################

- alias: Bedtime - Before 11:30p

  trigger:
    - platform: state
      entity_id: input_boolean.bedtime
      to: 'on'
      for:
        hours: 0
        minutes: 4
        seconds: 0

  condition:
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
    - condition: state
      entity_id: input_boolean.thermostat_away
      state: 'off'
    - condition: time
      after: '17:00'
      before: '23:30'

  action:
    - service: climate.set_hold_mode
      data:
        entity_id: climate.main_floor
        hold_mode: "sleep"

        ##########################################################
        ## Bedtime after Midnight
        ##########################################################

- alias: Bedtime - After Midnight

  trigger:
    - platform: state
      entity_id: input_boolean.bedtime
      to: 'on'
      for:
        hours: 0
        minutes: 4
        seconds: 0

  condition:
    - condition: time
      after: '00:00'
      before: '06:00'
    - condition: state
      entity_id: input_select.holiday
      state: 'None'

  action:
    - service: light.turn_off
      entity_id:
        - light.front_porch
        - light.back_door
        - light.garage_light
        - light.backyard_deck
    - service: switch.turn_off
      entity_id:
        - switch.lower_backyard_lighting
        - switch.backyard_patio_lighting

        ##########################################################
        ## Bedtime after Midnight Holiday
        ##########################################################

- alias: Bedtime - After Midnight Holiday

  trigger:
    - platform: state
      entity_id: input_boolean.bedtime
      to: 'on'
      for:
        hours: 0
        minutes: 4
        seconds: 0

  condition:
    - condition: time
      after: '00:00'
      before: '06:00'
    - condition: or
      conditions:
        - condition: state
          entity_id: input_select.holiday
          state: 'Halloween'
        - condition: state
          entity_id: input_select.holiday
          state: "St. Patrick's Day"
        - condition: state
          entity_id: input_select.holiday
          state: 'Easter'
        - condition: state
          entity_id: input_select.holiday
          state: "Valentine's Day"
        - condition: state
          entity_id: input_select.holiday
          state: 'Thanksgiving'
        - condition: state
          entity_id: input_select.holiday
          state: 'Labor Day'
        - condition: state
          entity_id: input_select.holiday
          state: 'Memorial Day'
        - condition: state
          entity_id: input_select.holiday
          state: 'Independence Day'
        - condition: state
          entity_id: input_select.holiday
          state: 'Veterans Day'
        - condition: state
          entity_id: input_select.holiday
          state: 'Christmas'

  action:
    - service: light.turn_off
      entity_id:
        - light.back_door
        - light.garage_light
    - service: switch.turn_off
      entity_id:
        - switch.lower_backyard_lighting
        - switch.backyard_patio_lighting

        ##########################################################
        ## Portable AC Bedtime
        ##########################################################

- alias: Bedtime - Portable AC Bedtime

  trigger:
    - platform: state
      entity_id: input_boolean.bedtime
      to: 'on'
      for:
        hours: 0
        minutes: 4
        seconds: 0

  condition:
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
    - condition: state
      entity_id: input_boolean.disable_portable_ac
      state: 'off'
    - condition: state
      entity_id: group.overnight_guests
      state: 'not_home'
    - condition: state
      entity_id: input_boolean.portable_ac
      state: 'on'

  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.portable_ac

        ##########################################################
        ## Reset Bedtime Switch
        ##########################################################

- alias: Bedtime - Reset Switch

  trigger:
    - platform: state
      entity_id: input_boolean.bedtime
      from: 'off'
      to: 'on'
      for:
        hours: 0
        minutes: 6
        seconds: 0

  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.bedtime
