        ##########################################################
        ## Set USER2 as Working
        ##########################################################

- alias: Calendar - Set USER2 as Working

  trigger:
    - platform: numeric_state
      entity_id: sensor.USER2_work_offset
      below: '25200'

  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.USER2_working

        ##########################################################
        ## Reset USER2 as Working at 9p
        ##########################################################

- alias: Calendar - Reset USER2 as Working at 9p

  trigger:
    - platform: time
      after: '21:00'

  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.USER2_working

        ##########################################################
        ## Reset USER2 as Working at 11p (second pass)
        ##########################################################

- alias: Calendar - Reset USER2 as Working at 11p

  trigger:
    - platform: time
      after: '23:00'

  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.USER2_working
