#################################################################
## Doorbell Automations
#################################################################

        ##########################################################
        ## Turn On Front Porch Lights when Doorbell Rings
        ##########################################################

- alias: Doorbell - Turn On Front Porch Lights when Rung
  id: 'doorbell_turn_on_front_porch_lights_when_rung'

  trigger:
    - platform: state
      entity_id: binary_sensor.ring_front_door_ding
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.disable_doorbell
      state: 'off'

  action:
    - service: light.turn_on
      entity_id:
        - light.front_porch
      data:
        brightness_pct: 100

        ##########################################################
        ## Reset Front Porch Lights Brightness After Doorbell Rings
        ##########################################################

- alias: Doorbell - Reset Front Porch Lights Brightness After Ring
  id: 'doorbell_reset_front_porch_lights_brightness_after_ring'

  trigger:
    - platform: state
      entity_id: binary_sensor.ring_front_door_ding
      from: 'on'
      to: 'off'
      for:
        hours: 0
        minutes: 15
        seconds: 0

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.disable_doorbell
      state: 'off'

  action:
    - service: light.turn_on
      entity_id:
        - light.front_porch
      data:
        brightness_pct: 50
        transition: 900

        ##########################################################
        ## Turn On Front Porch Lights when Motion Detected
        ##########################################################

- alias: Doorbell - Turn On Front Porch Lights when Motion Detected
  id: 'doorbell_turn_on_front_porch_lights_when_motion_detected'

  trigger:
    - platform: state
      entity_id: binary_sensor.ring_front_door_motion
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.front_porch_person_detected
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.disable_doorbell
      state: 'off'

  action:
    - service: light.turn_on
      entity_id:
        - light.front_porch
      data:
        brightness_pct: 100

        ##########################################################
        ## Reset Front Porch Lights Brightness After Motion Detected
        ##########################################################

- alias: Doorbell - Reset Front Porch Lights Brightness After Motion Detected
  id: 'doorbell_reset_front_porch_lights_brightness_after_motion_detected'

  trigger:
    - platform: state
      entity_id: binary_sensor.ring_front_door_motion
      from: 'on'
      to: 'off'
      for:
        hours: 0
        minutes: 15
        seconds: 0
    - platform: state
      entity_id: binary_sensor.front_porch_person_detected
      from: 'on'
      to: 'off'
      for:
        hours: 0
        minutes: 15
        seconds: 0

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.disable_doorbell
      state: 'off'
    - condition: state
      entity_id: light.front_porch
      state: 'on'
      for:
        hours: 0
        minutes: 30
        seconds: 0

  action:
    - service: light.turn_on
      entity_id:
        - light.front_porch
      data:
        brightness_pct: 50
        transition: 900

        ##########################################################
        ## Turn On Lights when Doorbell Rings and Away
        ##########################################################

- alias: Doorbell - Turn On Lights when Ring and Away
  id: 'doorbell_turn_on_lights_when_ring_and_away'

  trigger:
    - platform: state
      entity_id: binary_sensor.ring_front_door_ding
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.disable_doorbell
      state: 'off'
    - condition: not
      conditions:
      - condition: state
        entity_id: group.household
        state: 'home'

  action:
    - service: light.turn_on
      entity_id:
        - light.living_room_lamps
      data:
        brightness_pct: 100
        color_temp: 370
    - service: light.turn_on
      entity_id:
        - light.kitchen_sink
      data:
        brightness_pct: 100
    - service: light.turn_on
      entity_id:
        - light.back_door
      data:
        brightness_pct: 100
    - service: light.turn_on
      entity_id:
        - light.garage_light
      data:
        brightness_pct: 100

        ##########################################################
        ## Turn Off Lights After Doorbell Rings and Away
        ##########################################################

- alias: Doorbell - Turn Off Lights After Ring and Away
  id: 'doorbell_turn_off_lights_after_ring_and_away'

  trigger:
    - platform: state
      entity_id: binary_sensor.ring_front_door_ding
      from: 'on'
      to: 'off'
      for:
        hours: 0
        minutes: 15
        seconds: 0

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.disable_doorbell
      state: 'off'
    - condition: not
      conditions:
      - condition: state
        entity_id: group.household
        state: 'home'

  action:
    - service: light.turn_off
      entity_id:
        - light.living_room_lights
      data:
        transition: 900
    - service: light.turn_off
      entity_id:
        - light.kitchen_sink
    - service: light.turn_on
      entity_id:
        - light.back_door
      data:
        brightness_pct: 1
    - service: light.turn_on
      entity_id:
        - light.garage_light
      data:
        brightness_pct: 1

        ##########################################################
        ## Turn On Lights when Motion Detected and Away
        ##########################################################

- alias: Doorbell - Turn On Lights when Motion Detected and Away
  id: 'doorbell_turn_on_lights_when_motion_detected_and_away'

  trigger:
    - platform: state
      entity_id: binary_sensor.ring_front_door_motion
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.front_porch_person_detected
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.disable_doorbell
      state: 'off'
    - condition: not
      conditions:
      - condition: state
        entity_id: group.household
        state: 'home'

  action:
    - service: light.turn_on
      entity_id:
        - light.living_room_lamps
      data:
        brightness_pct: 100
        color_temp: 370
    - service: light.turn_on
      entity_id:
        - light.kitchen_sink
      data:
        brightness_pct: 100
    - service: light.turn_on
      entity_id:
        - light.back_door
      data:
        brightness_pct: 100
    - service: light.turn_on
      entity_id:
        - light.garage_light
      data:
        brightness_pct: 100

        ##########################################################
        ## Turn Off Lights After Motion Detected and Away
        ##########################################################

- alias: Doorbell - Turn Off Lights After Motion Detected and Away
  id: 'doorbell_turn_off_lights_after_motion_dtected_and_away'

  trigger:
    - platform: state
      entity_id: binary_sensor.ring_front_door_motion
      from: 'on'
      to: 'off'
      for:
        hours: 0
        minutes: 15
        seconds: 0
    - platform: state
      entity_id: binary_sensor.front_porch_person_detected
      from: 'on'
      to: 'off'
      for:
        hours: 0
        minutes: 15
        seconds: 0

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.disable_doorbell
      state: 'off'
    - condition: not
      conditions:
      - condition: state
        entity_id: group.household
        state: 'home'

  action:
    - service: light.turn_off
      entity_id:
        - light.living_room_lights
      data:
        transition: 900
    - service: light.turn_off
      entity_id:
        - light.kitchen_sink
    - service: light.turn_on
      entity_id:
        - light.back_door
      data:
        brightness_pct: 1
    - service: light.turn_on
      entity_id:
        - light.garage_light
      data:
        brightness_pct: 1

#################################################################
## Notifications
#################################################################

        ##########################################################
        ## Doorbell Ring iOS USER1 Notification
        ##########################################################

- alias: Doorbell - Ring iOS USER1 Notification
  id: 'doorbell_ring_ios_USER1_notification'

  trigger:
    - platform: state
      entity_id: binary_sensor.ring_front_door_ding
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'
      
  action:
    - service: notify.USER1_devices
      data:
        message: Someone is at the Front Door
        data:
          tag: doorbell
          group: doorbell
          entity_id: camera.front_porch
          actions:
            - action: "unlock_front_door"
              title: "Unlock Front Door"
              destructive: true

        ##########################################################
        ## Doorbell Ring iOS USER2 Notification
        ##########################################################

- alias: Doorbell - Ring iOS USER2 Notification
  id: 'doorbell_ring_ios_USER2_notification'

  trigger:
    - platform: state
      entity_id: binary_sensor.ring_front_door_ding
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'
      
  action:
    - service: notify.USER2_devices
      data:
        message: Someone is at the Front Door
        data:
          tag: doorbell
          group: doorbell
          entity_id: 
           - camera.front_porch
          actions:
            - action: "unlock_front_door"
              title: "Unlock Front Door"
              destructive: true

        ##########################################################
        ## Ring Battery Low
        ##########################################################

- alias: Doorbell - Ring Battery Low
  id: 'doorbell_ring_battery_low'

  trigger:
    - platform: numeric_state
      entity_id: sensor.ring_front_door_battery
      below: 31
      for:
        hours: 1
        minutes: 0
        seconds: 0

  condition:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: notify.USER1_devices
      data:
        message: Ring Battery Low, Replace Battery Soon
        data:
          tag: doorbell-battery
          group: doorbell