#################################################################
## Door Automations
#################################################################

        ##########################################################
        ## Turn On Front Porch when Front Door Opens
        ##########################################################

- alias: Doors - Turn on Front Porch when Front Opens

  trigger:
    - platform: state
      entity_id: binary_sensor.front_door_opened
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.disable_door_open_lights_on
      state: 'off'

  action:
    - service: light.turn_on
      entity_id:
        - light.front_porch
      data:
        brightness_pct: 100

        ##########################################################
        ## Reset Front Door Brightness when Front Door Closes
        ##########################################################

- alias: Doors - Reset Front Porch Brightness when Front Closes

  trigger:
    - platform: state
      entity_id: binary_sensor.front_door_opened
      from: 'on'
      to: 'off'
      for:
        hours: 0
        minutes: 5
        seconds: 0

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.disable_door_open_lights_on
      state: 'off'
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: input_select.holiday
      state: 'None'

  action:
    - service: light.turn_on
      entity_id:
        - light.front_porch
      data:
        brightness_pct: 50
        transition: 120

        ##########################################################
        ## Turn off Front Porch when Door Closes between 12-5a
        ##########################################################

- alias: Doors - Turn off Front Porch when Front Closes between 12-5a

  trigger:
    - platform: state
      entity_id: binary_sensor.front_door_opened
      from: 'on'
      to: 'off'
      for:
        hours: 0
        minutes: 15
        seconds: 0

  condition:
    - condition: time
      after: '00:00'
      before: '05:00'
    - condition: state
      entity_id: input_boolean.disable_door_open_lights_on
      state: 'off'
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: input_select.holiday
      state: 'None'

  action:
    - service: light.turn_off
      entity_id:
        - light.front_porch
      data:
        transition: 900

        ##########################################################
        ## Turn On Living Room when Front Door Opens
        ##########################################################

- alias: Doors - Turn on Living Room when Front Opens

  trigger:
    - platform: state
      entity_id: binary_sensor.front_door_opened
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.disable_door_open_lights_on
      state: 'off'

  action:
    - service: light.turn_on
      entity_id:
        - light.living_room_lights
      data:
       color_temp: 447
       brightness_pct: 100

        ##########################################################
        ## Turn on Back Door Lights when Door Opens
        ##########################################################

- alias: Doors - Turn on Back Door Lights when Door Opens

  trigger:
    - platform: state
      entity_id: binary_sensor.back_door_opened
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.disable_door_open_lights_on
      state: 'off'

  action:
    - service: light.turn_on
      entity_id:
        - light.back_door
      data:
       brightness_pct: 100

        ##########################################################
        ## Reset Back Door Brightness when Door Closes
        ##########################################################

- alias: Doors - Reset Back Brightness when Door Closes

  trigger:
    - platform: state
      entity_id: binary_sensor.back_door_opened
      from: 'on'
      to: 'off'
      for:
        hours: 0
        minutes: 10
        seconds: 0

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.disable_door_open_lights_on
      state: 'off'

  action:
    - service: light.turn_on
      entity_id:
        - light.back_door
      data:
        brightness_pct: 2
        transition: 300

        ##########################################################
        ## Turn off Back Door when Door Closes between 12-5a
        ##########################################################

- alias: Doors - Turn off Back when Door Closes between 12-5a

  trigger:
    - platform: state
      entity_id: binary_sensor.back_door_opened
      from: 'on'
      to: 'off'
      for:
        hours: 0
        minutes: 17
        seconds: 0

  condition:
    - condition: time
      after: '00:00'
      before: '05:00'
    - condition: state
      entity_id: input_boolean.disable_door_open_lights_on
      state: 'off'
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: group.friends_and_family
      state: 'not_home'

  action:
    - service: light.turn_off
      entity_id:
        - light.back_door
      data:
        transition: 900

        ##########################################################
        ## Turn on Basement Lights when Door Opens and Lights Off
        ##########################################################

- alias: Doors - Turn on Basement Lights when Door Opens and Lights Off

  trigger:
    - platform: state
      entity_id: binary_sensor.basement_door_opened
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: light.basement_lighting
      state: 'off'
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.disable_door_open_lights_on
      state: 'off'
    - condition: state
      entity_id: group.household
      state: 'home'

  action:
    - service: light.turn_on
      entity_id:
        - light.basement_lights
        - light.basement_stairs
        - light.laundry_room_light
        - light.craft_room_ceiling
        - light.basement_storage_area_ceiling
      data:
        brightness_pct: 100
    - service: light.turn_on
      entity_id:
        - light.work_bench_light
      data:
       brightness_pct: 2
