#################################################################
## Door Lock Automations
#################################################################

        ##########################################################
        ## Lock Front Door After 30 Mins
        ##########################################################

- alias: Locks - Lock Front Door After 30 Mins
  id: 'locks_lock_front_door_after_30_mins'

  trigger:
    - platform: state
      entity_id: lock.front_door
      from: 'locked'
      to: 'unlocked'
      for:
        hours: 0
        minutes: 30
        seconds: 0

  condition:
    - condition: state
      entity_id: input_boolean.disable_lock_unlock_doors
      state: 'off'
    - condition: state
      entity_id: binary_sensor.front_door_opened
      state: 'off'
    - condition: state
      entity_id: lock.front_door
      state: 'unlocked'

  action:
    - service: lock.lock
      entity_id: lock.front_door

        ##########################################################
        ## Lock Back Door After 2 Hours
        ##########################################################

- alias: Locks - Lock Back Door After 2 Hours
  id: 'locks_lock_back_door_after_2_hours'

  trigger:
    - platform: state
      entity_id: lock.back_door
      from: 'locked'
      to: 'unlocked'
      for:
        hours: 2
        minutes: 0
        seconds: 0

  condition:
    - condition: state
      entity_id: input_boolean.disable_lock_unlock_doors
      state: 'off'
    - condition: state
      entity_id: binary_sensor.back_door_opened
      state: 'off'
      for:
        hours: 1
        minutes: 0
        seconds: 0
    - condition: state
      entity_id: lock.back_door
      state: 'unlocked'

  action:
    - service: lock.lock
      entity_id: lock.back_door

        ##########################################################
        ## Lock Basement Door After 2 hours
        ##########################################################

- alias: Locks - Lock Basement Door After 45 Mins
  id: 'locks_lock_basement_door_after_45_mins'

  trigger:
    - platform: state
      entity_id: lock.basement_door
      from: 'locked'
      to: 'unlocked'
      for:
        hours: 2
        minutes: 0
        seconds: 0

  condition:
    - condition: state
      entity_id: input_boolean.disable_lock_unlock_doors
      state: 'off'
    - condition: state
      entity_id: binary_sensor.basement_door_opened
      state: 'off'
      for:
        hours: 1
        minutes: 0
        seconds: 0
    - condition: state
      entity_id: lock.basement_door
      state: 'unlocked'

  action:
    - service: lock.lock
      entity_id: lock.basement_door

        ##########################################################
        ## Lock Doors at 2a
        ##########################################################

- alias: Locks - Lock Doors at 2a
  id: 'locks_lock_back_door_at_2a'

  trigger:
    - platform: time
      at: '02:00:00'

  condition:
    - condition: state
      entity_id: input_boolean.disable_lock_unlock_doors
      state: 'off'
    - condition: state
      entity_id: binary_sensor.doors
      state: 'off'

  action:
    - service: lock.lock
      entity_id:
       - lock.front_door
       - lock.back_door
       - lock.basement_door

#################################################################
## Notifications
#################################################################

        ##########################################################
        ## Locks Low Battery Notification
        ##########################################################

- alias: Locks - Low Battery Notification
  id: 'locks_low_battery_notification'

  mode: parallel
  trigger:
    - platform: numeric_state
      entity_id: 
          - sensor.front_door_lock_batt
          - sensor.back_door_lock_batt
          - sensor.basement_door_lock_batt
      below: 30
      for:
        hours: 1
        minutes: 0
        seconds: 0

  condition:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: notify.USER1_devices
      data:
        message: "{{ trigger.to_state.attributes.friendly_name }} Low"
        data:
          tag: battery
          group: battery