#################################################################
## Network
#################################################################

        ##########################################################
        ## Re-Enable Pi-hole After 30 Mins
        ##########################################################

- alias: Network - Re-Enable Pi-hole After 30 Mins
  id: 'network_reenable_pihole_after_30_mins'

  triggers:
    - trigger: state
      entity_id: input_boolean.pihole
      from: 'on'
      to: 'off'
      for:
        hours: 0
        minutes: 31
        seconds: 0

  conditions:
    - condition: state
      entity_id: input_boolean.pihole
      state: 'off'

  actions:
    - action: homeassistant.turn_on
      target:
        entity_id:
          - input_boolean.pihole

        ##########################################################
        ## Disable Pi-hole
        ##########################################################

- alias: Network - Disable Pi-hole
  id: 'network_disable_pihole'

  triggers:
    - trigger: state
      entity_id: input_boolean.pihole
      from: 'on'
      to: 'off'
      for:
        hours: 0
        minutes: 0
        seconds: 3

  conditions:
    - condition: state
      entity_id: input_boolean.pihole
      state: 'off'

  actions:
    - action: script.pihole_disable
      data: {}

        ##########################################################
        ## Enable Pi-hole
        ##########################################################

- alias: Network - Enable Pi-hole
  id: 'network_enable_pihole'

  triggers:
    - trigger: state
      entity_id: input_boolean.pihole
      from: 'off'
      to: 'on'
      for:
        hours: 0
        minutes: 0
        seconds: 3

  conditions:
    - condition: state
      entity_id: input_boolean.pihole
      state: 'on'

  actions:
    - action: script.pihole_enable
      data: {}

#################################################################
## Notifications
#################################################################

    #################################################################
    ## WAN Down Notification
    #################################################################

- alias: Network - WAN Down Notification
  id: 'network_wan_down_notification'

  triggers:
    - trigger: state
      entity_id: binary_sensor.wan
      to: 'off'
      for:
        hours: 0
        minutes: 1
        seconds: 0

  conditions:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  actions:
    - action: notify.USER1_devices
      data:
        message: Internet is Down!
        data:
          tag: network

    #################################################################
    ## WAN Up Notification
    #################################################################

- alias: Network - WAN Up Notification
  id: 'network_wan_up_notification'

  triggers:
    - trigger: state
      entity_id: binary_sensor.wan
      from: 'off'
      to: 'on'
      for:
        hours: 0
        minutes: 1
        seconds: 0

  conditions:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  actions:
    - action: notify.USER1_devices
      data:
        message: Internet is Up
        data:
          tag: network
