#################################################################
## Network
#################################################################

    #################################################################
    ## WAN Down Notification
    #################################################################

- alias: Network - WAN Down Notification
  id: 'network_wan_down_notification'

  trigger:
    - platform: state
      entity_id: binary_sensor.wan
      to: 'off'
      for:
        hours: 0
        minutes: 1
        seconds: 0

  condition:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: persistent_notification.create
      data:
        message: "Internet Down"
        title: "WAN"
        notification_id: "1"

    #################################################################
    ## WAN Up Notification
    #################################################################

- alias: Network - WAN Up Notification
  id: 'network_wan_up_notification'

  trigger:
    - platform: state
      entity_id: binary_sensor.wan
      from: 'off'
      to: 'on'
      for:
        hours: 0
        minutes: 1
        seconds: 0

  condition:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: persistent_notification.create
      data:
        message: "Internet Up"
        title: "WAN"
        notification_id: "1"

        ##########################################################
        ## WAN Down Power On at&t Router
        ##########################################################

- alias: Network - WAN Down Power On att Router
  id: 'network_wan_down_power_on_att_router'

  trigger:
    - platform: state
      entity_id: binary_sensor.wan
      to: 'off'
      for:
        hours: 0
        minutes: 1
        seconds: 0
    - platform: state
      entity_id: binary_sensor.wan
      to: 'off'
      for:
        hours: 0
        minutes: 5
        seconds: 0
    - platform: state
      entity_id: binary_sensor.wan
      to: 'off'
      for:
        hours: 0
        minutes: 10
        seconds: 0
    - platform: state
      entity_id: binary_sensor.wan
      to: 'off'
      for:
        hours: 0
        minutes: 15
        seconds: 0
    - platform: state
      entity_id: binary_sensor.wan
      to: 'off'
      for:
        hours: 0
        minutes: 20
        seconds: 0

  action:
    - service: switch.turn_on
      entity_id:
        - switch.att_router
    - service: notify.mobile_app_USER1s_iphone
      data:
        message: Internet is Down, Turning On at&t Router
        data:
          apns_headers:
           'apns-collapse-id': 'internets-down'

        ##########################################################
        ## WAN Up Power Off at&t Router
        ##########################################################

- alias: Network - WAN Up Power Off att Router
  id: 'network_wan_up_power_off_att_router'

  trigger:
    - platform: state
      entity_id: binary_sensor.wan
      to: 'on'
      for:
        hours: 0
        minutes: 30
        seconds: 0

  action:
    - service: switch.turn_off
      entity_id:
        - switch.att_router
    - service: notify.mobile_app_USER1s_iphone
      data:
        message: Internet is Up, Shutting Off at&t Router
        data:
          apns_headers:
           'apns-collapse-id': 'internets-up'

        #################################################################
        ## WAN Down On Startup Turn On at&t Router
        #################################################################

- alias: network - WAN Down On Startup Turn On att Router
  id: 'network_wan_down_on_startup_turn_on_att_router'

  trigger:
    - platform: homeassistant
      event: start

  condition:
    - condition: state
      entity_id: binary_sensor.wan
      state: 'off'

  action:
    - service: switch.turn_on
      entity_id:
        - switch.att_router
    - delay: 00:10:00
    - service: switch.turn_on
      entity_id:
        - switch.att_router
    - delay: 00:10:00
    - service: switch.turn_on
      entity_id:
        - switch.att_router

        ##########################################################
        ## Turn On at&t Router in Vacation Mode
        ##########################################################

- alias: network - Turn On att Router in Vacation Mode
  id: 'network_turn_on_att_router_in_vacation_mode'

  trigger:
    - platform: state
      entity_id: input_boolean.vacation_mode
      to: 'on'

  condition:
    - condition: state
      entity_id: input_boolean.disable_home_away
      state: 'off'

  action:
    - service: switch.turn_on
      entity_id: switch.att_router

        ##########################################################
        ## Turn Off at&t Router after Vacation Mode
        ##########################################################

- alias: network - Turn Off att Router after Vacation Mode
  id: 'network_turn_off_att_router_after_vacation_mode'

  trigger:
    - platform: state
      entity_id: input_boolean.vacation_mode
      to: 'off'

  condition:
    - condition: state
      entity_id: input_boolean.disable_home_away
      state: 'off'

  action:
    - service: switch.turn_off
      entity_id: switch.att_router

        ##########################################################
        ## Turn On at&t Router when Away
        ##########################################################

- alias: network - Turn On att Router when Away
  id: 'network_turn_on_att_router_when_away'

  trigger:
    - platform: state
      entity_id: group.household
      from: 'home'
      to: 'not_home'

  condition:
    - condition: state
      entity_id: input_boolean.disable_home_away
      state: 'off'

  action:
    - service: switch.turn_on
      entity_id:
        - switch.att_router

        ##########################################################
        ## Turn Off at&t Router when Home
        ##########################################################

- alias: network - Turn Off att Router when Home
  id: 'network_turn_off_att_router_when_home'

  trigger:
    - platform: state
      entity_id: group.household
      from: 'not_home'
      to: 'home'

  condition:
    - condition: state
      entity_id: input_boolean.disable_home_away
      state: 'off'

  action:
    - service: switch.turn_off
      entity_id:
        - switch.att_router

        ##########################################################
        ## Turn On Garage Fan (Network Cooling) when above 87 Degrees
        ##########################################################

- alias: network - Turn On Garage Fan when above 87 Degrees
  id: 'network_turn_on_garage_fan_when_above_87_degrees'

  trigger:
    - platform: numeric_state
      entity_id: sensor.garage_temperature
      above: 87

  action:
    - service: switch.turn_on
      entity_id:
        - switch.garage_fan

        ##########################################################
        ## Turn Off Garage Fan (Network Cooling) when below 87 Degrees
        ##########################################################

- alias: network - Turn Off Garage Fan when below 87 Degrees
  id: 'network_turn_off_garage_fan_when_below_87_degrees'

  trigger:
    - platform: numeric_state
      entity_id: sensor.garage_temperature
      below: 87

  action:
    - service: switch.turn_off
      entity_id:
        - switch.garage_fan

        ##########################################################
        ## Household Away Turn On Camera POE
        ##########################################################

- alias: Network - Household Away Turn On Camera POE
  id: 'network_household_away_turn_on_camera_poe'

  trigger:
    - platform: state
      entity_id: group.household
      from: 'home'
      to: 'not_home'
      for:
        hours: 0
        minutes: 1
        seconds: 0

  condition:
    - condition: state
      entity_id: input_boolean.disable_home_away
      state: 'off'

  action:
    - service: switch.turn_on
      entity_id:
        - switch.living_room_camera
        - switch.basement_camera

        ##########################################################
        ## Household Home Turn Off Camera POE
        ##########################################################

- alias: Network - Household Home Turn Off Camera POE
  id: 'network_household_home_turn_off_camera_poe'

  trigger:
    - platform: state
      entity_id: group.household
      from: 'not_home'
      to: 'home'
      for:
        hours: 0
        minutes: 1
        seconds: 0

  condition:
    - condition: state
      entity_id: input_boolean.disable_home_away
      state: 'off'

  action:
    - service: switch.turn_off
      entity_id:
        - switch.living_room_camera
        - switch.basement_camera

        ##########################################################
        ## Re-Enable Pi-hole After 15 Mins
        ##########################################################

- alias: Network - Re-Enable Pi-hole After 15 Mins
  id: 'network_reenable_pihole_after_15_mins'

  trigger:
    - platform: state
      entity_id: group.pihole
      from: 'on'
      to: 'off'
      for:
        hours: 0
        minutes: 15
        seconds: 0

  condition:
    - condition: state
      entity_id: group.pihole
      state: 'off'

  action:
    - service: homeassistant.turn_on
      entity_id:
        - group.pihole

#################################################################
## Notifications
#################################################################

        #################################################################
        ## REDACTED (REDACTED) VPN Offline iOS Notification
        #################################################################

- alias: Network - REDACTED VPN Offline iOS Notification
  id: 'network_REDACTED_vpn_offline_ios_notification'

  trigger:
    - platform: state
      entity_id: binary_sensor.REDACTED_vpn
      from: 'on'
      to: 'off'
      for:
        hours: 0
        minutes: 5
        seconds: 0

  condition:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: notify.mobile_app_USER1s_iphone
      data:
        message: REDACTED (REDACTED) VPN Offline
        data:
          apns_headers:
           'apns-collapse-id': 'network-vpn-offline'

        #################################################################
        ## REDACTED (REDACTED) VPN Offline iOS Notification
        #################################################################

- alias: Network - REDACTED VPN Offline iOS Notification
  id: 'network_REDACTED_vpn_offline_ios_notification'

  trigger:
    - platform: state
      entity_id: binary_sensor.REDACTED_vpn
      from: 'on'
      to: 'off'
      for:
        hours: 0
        minutes: 5
        seconds: 0

  condition:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: notify.mobile_app_USER1s_iphone
      data:
        message: REDACTED (REDACTED) VPN Offline
        data:
          apns_headers:
           'apns-collapse-id': 'network-vpn-offline'

        #################################################################
        ## REDACTED (REDACTED) VPN Offline iOS Notification
        #################################################################

- alias: Network - REDACTED VPN Offline iOS Notification
  id: 'network_REDACTED_vpn_offline_ios_notification'

  trigger:
    - platform: state
      entity_id: binary_sensor.REDACTED_vpn
      from: 'on'
      to: 'off'
      for:
        hours: 0
        minutes: 5
        seconds: 0

  condition:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: notify.mobile_app_USER1s_iphone
      data:
        message: REDACTED (REDACTED) VPN Offline
        data:
          apns_headers:
           'apns-collapse-id': 'network-vpn-offline'
