#################################################################
## Audio Notification Automations
#################################################################

        ##########################################################
        ## Alarm Audio Notification
        ##########################################################

- alias: Notification Audio - Alarm Audio

  trigger:
    - platform: state
      entity_id: input_boolean.alarm_tripped
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: group.household
      state: 'not_home'
    - condition: state
      entity_id: input_boolean.enable_security
      state: 'on'

  action:
    - service: script.turn_on
      entity_id: script.say
      data:
        variables:
          master: 'media_player.sonos_living_room'
          where: 'media_player.sonos_media_center, media_player.sonos_living_room, media_player.sonos_dining_room, media_player.sonos_kitchen, media_player.sonos_bathroom, media_player.sonos_bedroom, media_player.sonos_USER1s_office, media_player.sonos_USER2s_office, media_player.sonos_basement'
          volume: '1'
          what: 'You are not Authorized to be Here. Law Enforcement Has Been Notified!'

        ##########################################################
        ## Welcome Home USER1 Audio Greeting
        ##########################################################

- alias: Notification Audio - Welcome Home USER1

  trigger:
    - platform: state
      entity_id: group.doors
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: device_tracker.USER1DEVICE
      state: 'home'
    - condition: state
      entity_id: input_boolean.USER1_greeting
      state: 'on'
    - condition: state
      entity_id: input_boolean.disable_voice_greeting
      state: 'off'
    - condition: time
      after: '09:00'
      before: '22:00'

  action:
    - delay: '00:00:04'
    - service: script.turn_on
      entity_id: script.say
      data:
        variables:
          master: 'media_player.sonos_living_room'
          where: 'media_player.sonos_living_room, media_player.sonos_dining_room, media_player.sonos_kitchen'
          volume: '0.5'
          what: 'Welcome home, USER1.'
    - delay: '00:02:00'
    - service: homeassistant.turn_off
      entity_id: input_boolean.USER1_greeting

        ##########################################################
        ## Notify USER2s Office that USER1 is Home
        ##########################################################

- alias: Notification Audio - Notify USER2s Office that USER1 is Home

  trigger:
    - platform: state
      entity_id: group.doors
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: device_tracker.USER1DEVICE
      state: 'home'
    - condition: state
      entity_id: device_tracker.USER2DEVICE
      state: 'home'
    - condition: state
      entity_id: input_boolean.USER1_greeting
      state: 'on'
    - condition: state
      entity_id: input_boolean.USER2_greeting
      state: 'off'
    - condition: state
      entity_id: binary_sensor.USER2_office_occupancy
      state: 'on'
    - condition: state
      entity_id: input_boolean.disable_voice_greeting
      state: 'off'
    - condition: time
      after: '09:00'
      before: '22:00'

  action:
    - delay: '00:00:60'
    - service: script.turn_on
      entity_id: script.say
      data:
        variables:
          master: 'media_player.sonos_USER2s_office'
          where: 'media_player.sonos_USER2s_office'
          volume: '0.5'
          what: 'USER1, is Home.'

        ##########################################################
        ## Welcome Home USER2 Audio Greeting
        ##########################################################

- alias: Notification Audio - Welcome Home USER2

  trigger:
    - platform: state
      entity_id: group.doors
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: device_tracker.USER2DEVICE
      state: 'home'
    - condition: state
      entity_id: input_boolean.USER2_greeting
      state: 'on'
    - condition: state
      entity_id: input_boolean.disable_voice_greeting
      state: 'off'
    - condition: time
      after: '09:00'
      before: '22:00'

  action:
    - delay: '00:00:04'
    - service: script.turn_on
      entity_id: script.say
      data:
        variables:
          master: 'media_player.sonos_living_room'
          where: 'media_player.sonos_living_room, media_player.sonos_dining_room, media_player.sonos_kitchen'
          volume: '0.5'
          what: 'Welcome home, USER2.'
    - delay: '00:02:00'
    - service: homeassistant.turn_off
      entity_id: input_boolean.USER2_greeting

        ##########################################################
        ## Notify USER1s Office that USER2 is Home
        ##########################################################

- alias: Notification Audio - Notify USER1s Office that USER2 is Home

  trigger:
    - platform: state
      entity_id: group.doors
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: device_tracker.USER1DEVICE
      state: 'home'
    - condition: state
      entity_id: device_tracker.USER2DEVICE
      state: 'home'
    - condition: state
      entity_id: input_boolean.USER1_greeting
      state: 'off'
    - condition: state
      entity_id: input_boolean.USER2_greeting
      state: 'on'
    - condition: state
      entity_id: binary_sensor.office_occupancy
      state: 'on'
    - condition: state
      entity_id: input_boolean.disable_voice_greeting
      state: 'off'
    - condition: time
      after: '09:00'
      before: '22:00'

  action:
    - delay: '00:00:60'
    - service: script.turn_on
      entity_id: script.say
      data:
        variables:
          master: 'media_player.sonos_USER1s_office'
          where: 'media_player.sonos_USER1s_office'
          volume: '0.5'
          what: 'USER2, is Home'

        ##########################################################
        ## Welcome Home USER1 and USER2 Audio Greeting
        ##########################################################

- alias: Notification Audio - Welcome Home USER1 and USER2 Audio Greeting

  trigger:
    - platform: state
      entity_id: group.doors
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: device_tracker.USER1DEVICE
      state: 'home'
    - condition: state
      entity_id: device_tracker.USER2DEVICE
      state: 'home'
    - condition: state
      entity_id: input_boolean.USER1_greeting
      state: 'on'
    - condition: state
      entity_id: input_boolean.USER2_greeting
      state: 'on'
    - condition: state
      entity_id: input_boolean.disable_voice_greeting
      state: 'off'
    - condition: time
      after: '09:00'
      before: '22:00'

  action:
    - delay: '00:00:03'
    - service: script.turn_on
      entity_id: script.say
      data:
        variables:
          master: 'media_player.sonos_living_room'
          where: 'media_player.sonos_living_room, media_player.sonos_dining_room, media_player.sonos_kitchen'
          volume: '0.5'
          what: 'Welcome Home, USER1 and USER2'
    - delay: '00:02:00'
    - service: homeassistant.turn_off
      entity_id: input_boolean.USER1_greeting, input_boolean.USER2_greeting

        #################################################################
        ## USER2 Left Work Audio Notification
        #################################################################

- alias: Notification Audio - USER2 Left Work

  trigger:
    - platform: state
      entity_id: device_tracker.USER2DEVICE
      from: 'work'
      to: 'not_home'

  condition:
    - condition: state
      entity_id: device_tracker.USER1DEVICE
      state: 'home'
    - condition: state
      entity_id: device_tracker.USER2DEVICE
      state: 'not_home'
    - condition: state
      entity_id: input_boolean.USER2_away
      state: 'on'
    - condition: state
      entity_id: input_boolean.disable_voice_greeting
      state: 'off'
    - condition: time
      after: '09:00'
      before: '22:00'

  action:
    - service: media_player.sonos_snapshot
      data:
        with_group: yes
    - delay: '00:00:03'
    - service: media_player.sonos_unjoin
      entity_id:
        - media_player.sonos_living_room
        - media_player.sonos_dining_room
        - media_player.sonos_kitchen
        - media_player.sonos_bathroom
        - media_player.sonos_USER1s_office
    - delay: '00:00:01'
    - service: media_player.sonos_join
      data:
        master: media_player.sonos_USER1s_office
      entity_id:
        - media_player.sonos_living_room
        - media_player.sonos_dining_room
        - media_player.sonos_kitchen
        - media_player.sonos_bathroom
        - media_player.sonos_bedroom
        - media_player.sonos_USER1s_office
    - delay: '00:00:01'
    - service: media_player.volume_set
      entity_id:
        - media_player.sonos_living_room
        - media_player.sonos_dining_room
        - media_player.sonos_kitchen
        - media_player.sonos_bathroom
        - media_player.sonos_bedroom
        - media_player.sonos_USER1s_office
      data:
        volume_level: '0.6'
    - delay: '00:00:02'
    - service: tts.amazon_polly_say
      data_template:
        entity_id: media_player.sonos_USER1s_office
        message: "USER2 has left work, and will arrive Home in about, {{states('sensor.USER2_to_home')}} minutes"
    - delay: '00:00:25'
    - service: media_player.sonos_restore
      data:
        with_group: yes
