#################################################################
## Text Notification Automations
#################################################################

    #################################################################
    ## Alarm Notifications
    #################################################################

- alias: Notification Text - Security

  trigger:
    - platform: state
      entity_id: input_boolean.alarm_tripped
      from: 'off'
      to: 'on'

  action:
    - service: persistent_notification.create
      data:
        message: "Alarm Has Been Tripped!"
        title: "Alarm"
        notification_id: "1"


- alias: Notification Text - Alarm

  trigger:
    - platform: state
      entity_id: input_boolean.alarm_tripped
      from: 'off'
      to: 'on'

  action:
    - service: notify.ios_USER1s_iphone
      data:
        message: Alarm Tripped
        data:
          push:
            category: camera
          entity_id: camera.garage_camera

        #################################################################
        ## USER1 Home Notification
        #################################################################

- alias: Notification Text - USER1 Home

  trigger:
    - platform: state
      entity_id: device_tracker.USER1DEVICE
      from: 'not_home'
      to: 'home'

  action:
    - service: notify.ios_USER1s_iphone
      data:
        message: USER1 Home

        #################################################################
        ## USER1 Away Notification
        #################################################################

- alias: Notification Text - USER1 Away

  trigger:
    - platform: state
      entity_id: device_tracker.USER1DEVICE
      from: 'home'
      to: 'not_home'

  action:
    - service: notify.ios_USER1s_iphone
      data:
        message: USER1 Away

        #################################################################
        ## USER2 Home Notification
        #################################################################

- alias: Notification Text - USER2 Home

  trigger:
    - platform: state
      entity_id: device_tracker.USER2DEVICE
      from: 'not_home'
      to: 'home'

  action:
    - service: notify.ios_USER1s_iphone
      data:
        message: USER2 Home

        #################################################################
        ## USER2 Away Notification
        #################################################################

- alias: Notification Text - USER2 Away

  trigger:
    - platform: state
      entity_id: device_tracker.USER2DEVICE
      from: 'home'
      to: 'not_home'

  action:
    - service: notify.ios_USER1s_iphone
      data:
        message: USER2 Away

        #################################################################
        ## USER2 Left Work Notification
        #################################################################

- alias: Notification Text - USER2 Left Work

  trigger:
    - platform: state
      entity_id: device_tracker.USER2DEVICE
      from: 'work'
      to: 'not_home'

  action:
    - service: notify.ios_USER1s_iphone
      data:
        message: USER2 has left Work

        #################################################################
        ## Motion Alarm Notification
        #################################################################

- alias: Notification Text - Motion Based Alarm

  trigger:
    - platform: state
      entity_id: group.alarm_occupancy
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: group.household
      state: 'not_home'

  action:
    - service: notify.ios_USER1s_iphone
      data:
        message: Motion Detected
        data:
          push:
            category: camera
          entity_id: camera.garage_camera

        #################################################################
        ## Door Alarm Notification
        #################################################################

- alias: Notification Text - Door Open Alarm

  trigger:
    - platform: state
      entity_id: group.doors
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: group.household
      state: 'not_home'

  action:
    - service: notify.ios_USER1s_iphone
      data:
        message: Door Opened
        data:
          push:
            category: camera
          entity_id: camera.garage_camera

        #################################################################
        ## Fireplace Alarm Notification
        #################################################################

- alias: Notification Text - Fireplace On when Nobody Home

  trigger:
    - platform: state
      entity_id: switch.fireplace
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: group.household
      state: 'not_home'

  action:
    - service: notify.ios_USER1s_iphone
      data:
        message: Fireplace Turned On!

        #################################################################
        ## Home Assistant Started Notification
        #################################################################

- alias: Notification Text - Home Assistant Start

  trigger:
    - platform: event
      event_type: homeassistant_start

  action:
    - service: notify.ios_USER1s_iphone
      data:
        message: Home Assistant Started
