##################################################################
## Party Mode Automations
##################################################################

        ##########################################################
        ## Living Room Random Colors On
        ##########################################################

- alias: Party - Set Living Room to Random Color

  trigger:
    - platform: state
      entity_id: input_boolean.livingroom_rainbow
      to: 'on'

  condition:
    - condition: state
      entity_id: group.household
      state: 'home'

  action:
    - service: light.turn_on
      entity_id:
        - light.living_room_lamps
        - light.media_center_lighting
        - light.globe
      data:
        effect: random
        brightness_pct: 100
    - delay: '00:00:05'
    - service: light.turn_on
      entity_id: light.living_room_lamp_1
      data:
        effect: colorloop
        brightness_pct: 100
    - delay: '00:00:17'
    - service: light.turn_on
      entity_id: light.media_center_lighting
      data:
        effect: colorloop
        brightness_pct: 100
    - delay: '00:00:31'
    - service: light.turn_on
      entity_id: light.globe
      data:
        effect: colorloop
        brightness_pct: 100
    - delay: '00:00:43'
    - service: light.turn_on
      entity_id: light.living_room_lamp_2
      data:
        effect: colorloop
        brightness_pct: 100

        ##########################################################
        ## Living Room Random Colors Off
        ##########################################################

- alias: Party - Set Living Room to Random Color Off

  trigger:
    - platform: state
      entity_id: input_boolean.livingroom_rainbow
      to: 'off'

  condition:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: input_boolean.bedtime
      state: 'off'
    - condition: state
      entity_id: light.living_room_lights
      state: 'on'

  action:
    - service: light.turn_on
      entity_id:
        - light.living_room_lights
      data:
        effect: stop
    - delay: '00:00:05'
    - service: light.turn_on
      entity_id:
        - light.living_room_lamps
      data:
        effect: stop
        transition: 30
        brightness_pct: 100
        color_temp: 447
    - service: light.turn_on
      entity_id: light.media_center_lighting
      data:
        transition: 30
        effect: random
        brightness_pct: 100
    - service: light.turn_on
      entity_id:
        - light.globe
      data:
        effect: stop
        transition: 30
        brightness_pct: 20
        color_temp: 366

        ##########################################################
        ## Bedroom Random Colors On
        ##########################################################

- alias: Party - Set Bedroom to Random Color

  trigger:
    - platform: state
      entity_id: input_boolean.bedroom_rainbow
      to: 'on'

  condition:
    - condition: state
      entity_id: group.household
      state: 'home'

  action:
    - service: light.turn_on
      entity_id:
        - light.USER1s_nightstand
        - light.USER2s_nightstand
        - light.bedroom_lamp
      data:
        effect: random
        brightness_pct: 100
    - service: light.turn_off
      entity_id:
        - light.closet_lamp
        - light.bedroom_closet_ceiling
    - delay: '00:00:05'
    - service: light.turn_on
      entity_id: light.USER1s_nightstand
      data:
        effect: colorloop
        brightness_pct: 100
    - delay: '00:00:17'
    - service: light.turn_on
      entity_id: light.bedroom_lamp
      data:
        effect: colorloop
        brightness_pct: 100
    - delay: '00:00:31'
    - service: light.turn_on
      entity_id: light.USER2s_nightstand
      data:
        effect: colorloop
        brightness_pct: 100

        ##########################################################
        ## Bedroom Random Colors Off
        ##########################################################

- alias: Party - Set Bedroom to Random Color Off

  trigger:
    - platform: state
      entity_id: input_boolean.bedroom_rainbow
      to: 'off'

  condition:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: input_boolean.bedtime
      state: 'off'
    - condition: state
      entity_id: light.bedroom_lights
      state: 'on'

  action:
    - service: light.turn_on
      entity_id:
        - light.USER1s_nightstand
        - light.USER2s_nightstand
        - light.bedroom_lamp
      data:
        effect: stop
    - delay: '00:00:05'
    - service: light.turn_on
      entity_id:
        - light.USER1s_nightstand
        - light.USER2s_nightstand
        - light.bedroom_lamp
      data:
        effect: stop
        transition: 30
        color_temp: 447
        brightness_pct: 50
    - service: light.turn_on
      entity_id:
        - light.closet_lamp
        - light.bedroom_closet_ceiling
      data:
        effect: stop
        transition: 30
        brightness_pct: 50

        ##########################################################
        ## Office Random Colors On
        ##########################################################

- alias: Party - Set Office to Random Color On

  trigger:
    - platform: state
      entity_id: input_boolean.office_rainbow
      to: 'on'

  condition:
    - condition: state
      entity_id: input_boolean.office_rainbow
      state: 'on'

  action:
    - service: light.turn_on
      entity_id: light.office_lamp
      data:
        effect: colorloop
        transition: 30
        brightness_pct: 100

        ##########################################################
        ## Office Random Colors Off
        ##########################################################

- alias: Party - Set Office Random Colors Off

  trigger:
    - platform: state
      entity_id: input_boolean.office_rainbow
      to: 'off'

  condition:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: input_boolean.bedtime
      state: 'off'
    - condition: state
      entity_id: light.office_lamp
      state: 'on'

  action:
    - service: light.turn_on
      entity_id: light.office_lamp
      data:
        effect: stop
        transition: 30
        color_temp: 447
        brightness_pct: 100

        ##########################################################
        ## Front Porch Random Colors On
        ##########################################################

- alias: Party - Set Front Porch to Random Color

  trigger:
    - platform: state
      entity_id: input_boolean.front_porch_rainbow
      to: 'on'

  condition:
    - condition: state
      entity_id: input_boolean.bedtime
      state: 'off'

  action:
    - service: light.turn_on
      entity_id:  light.front_porch_left
      data:
        effect: random
        brightness_pct: 100
    - service: light.turn_on
      entity_id: light.front_porch_right
      data:
        effect: random
        brightness_pct: 100
    - delay: '00:00:05'
    - service: light.turn_on
      entity_id: light.front_porch_left
      data:
        effect: colorloop
        brightness_pct: 100
    - delay: '00:00:23'
    - service: light.turn_on
      entity_id: light.front_porch_right
      data:
        effect: colorloop
        brightness_pct: 100

        ##########################################################
        ## Front Porch Random Colors Off
        ##########################################################

- alias: Party - Set Front Porch Random Colors Off

  trigger:
    - platform: state
      entity_id: input_boolean.front_porch_rainbow
      to: 'off'

  condition:
    - condition: state
      entity_id: light.front_porch
      state: 'on'

  action:
    - service: light.turn_on
      entity_id: light.front_porch
      data:
        effect: stop
    - delay: '00:00:01'
    - service: light.turn_on
      entity_id: light.front_porch
      data:
        effect: stop
        transition: 60
        brightness_pct: 40
        color_temp: 447
