#################################################################
## Vacation Mode Automations
#################################################################

        ##########################################################
        ## Turn on Vacation Mode when Gone 24 Hours
        ##########################################################

- alias: Vacation - Turn on when Gone 24 Hours

  trigger:
    - platform: state
      entity_id: group.household
      from: 'home'
      to: 'not_home'
      for:
        hours: 24
        minutes: 0
        seconds: 0

  condition:
    - condition: state
      entity_id: input_boolean.disable_home_away
      state: 'off'

  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.vacation_mode

        ##########################################################
        ## Turn off Vacation Mode when Home
        ##########################################################

- alias: Vacation - Turn off when Home

  trigger:
    - platform: state
      entity_id: group.household
      from: 'not_home'
      to: 'home'

  condition:
    - condition: state
      entity_id: input_boolean.disable_home_away
      state: 'off'

  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.vacation_mode

        ##########################################################
        ## Turn on Vacation Mode when on Vacation
        ##########################################################

- alias: Vacation - Turn on when on Vacation

  trigger:
    - platform: state
      entity_id: device_tracker.USER1DEVICE
      from: 'not_home'
      to: 'vacation'

  condition:
    - condition: state
      entity_id: input_boolean.disable_home_away
      state: 'off'

  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.vacation_mode

        ##########################################################
        ## Turn on Vacation Mode when at the Lake
        ##########################################################

- alias: Vacation - Turn on when at the Lake

  trigger:
    - platform: state
      entity_id: device_tracker.USER1DEVICE
      from: 'not_home'
      to: 'lake'

  condition:
    - condition: state
      entity_id: input_boolean.disable_home_away
      state: 'off'

  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.vacation_mode

        ##########################################################
        ## Turn off Vacation Mode when leaving the Lake
        ##########################################################

- alias: Vacation - Turn off when leaving the Lake

  trigger:
    - platform: state
      entity_id: device_tracker.USER1DEVICE
      from: 'lake'
      to: 'not_home'

  condition:
    - condition: state
      entity_id: input_boolean.disable_home_away
      state: 'off'

  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.vacation_mode

        ##########################################################
        ## Vacation Mode Scene
        ##########################################################

- alias: Vacation - Scene

  trigger:
    - platform: state
      entity_id: sun.sun
      from: 'above_horizon'
      to: 'below_horizon'

  condition:
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'on'

  action:
    - service: scene.turn_on
      entity_id: scene.vacation

        ##########################################################
        ## Vacation Mode Lights off at Midnight
        ##########################################################

- alias: Vacation - Lights Off Midnight

  trigger:
    - platform: time
      after: '00:12'

  condition:
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'on'

  action:
    - service: light.turn_off
      entity_id: light.kitchen_sink, group.living_room_lamps

        ##########################################################
        ## Vacation Mode Lights off at 10p
        ##########################################################

- alias: Vacation - Lights Off 10p

  trigger:
    - platform: time
      after: '22:07'

  condition:
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'on'

  action:
    - service: light.turn_off
      entity_id: light.office_ceiling, light.closet_lamp

        ##########################################################
        ## Vacation Mode Disable Automations
        ##########################################################

- alias: Vacation - Disable Automation

  trigger:
    - platform: state
      entity_id: input_boolean.vacation_mode
      from: 'off'
      to: 'on'

  action:
    - service: scene.turn_on
      entity_id: scene.vacation_disable_automation

        ##########################################################
        ## Vacation Mode Enable Automations
        ##########################################################

- alias: Vacation - Enable Automation

  trigger:
    - platform: state
      entity_id: input_boolean.vacation_mode
      from: 'on'
      to: 'off'

  action:
    - service: scene.turn_on
      entity_id: scene.vacation_enable_automation
