#################################################################
## Vacation Mode Automations
#################################################################

        ##########################################################
        ## Vacation Mode On
        ##########################################################

- alias: Vacation - Mode On
  id: 'vacation_mode_on'

  trigger:
    - platform: state
      entity_id: input_boolean.vacation_mode
      to: 'on'

  condition:
    - condition: not
      conditions:
      - condition: state
        entity_id: group.household
        state: 'home'
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'

  action:
    - service: homeassistant.turn_on
      entity_id:
       - input_boolean.disable_rainy_day
       - input_boolean.disable_interior_lights_sunset
       - input_boolean.disable_media_lights
       - input_boolean.disable_occupancy
       - input_boolean.disable_motion
       - input_boolean.disable_fountain

        ##########################################################
        ## Vacation Mode Off
        ##########################################################

- alias: Vacation - Mode Off
  id: 'vacation_mode_off'

  trigger:
    - platform: state
      entity_id: input_boolean.vacation_mode
      to: 'off'

  action:
    - service: homeassistant.turn_off
      entity_id:
       - input_boolean.disable_rainy_day
       - input_boolean.disable_interior_lights_sunset
       - input_boolean.disable_media_lights
       - input_boolean.disable_occupancy
       - input_boolean.thermostat_away
       - input_boolean.disable_motion

        ##########################################################
        ## Turn On Vacation Mode when Gone 24 Hours
        ##########################################################

- alias: Vacation - Turn On when Gone 24 Hours
  id: 'vacation_turn_on_when_gone_24_hours'

  trigger:
    - platform: state
      entity_id: group.household
      to: 'not_home'
      for:
        hours: 24
        minutes: 0
        seconds: 0

  condition:
    - condition: state
      entity_id: input_boolean.disable_home_away
      state: 'off'

  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.vacation_mode

        ##########################################################
        ## Turn off Vacation Mode when Home
        ##########################################################

- alias: Vacation - Turn off when Home
  id: 'vacation_turn_off_when_home'

  trigger:
    - platform: state
      entity_id: group.household
      from: 'not_home'
      to: 'home'

  condition:
    - condition: state
      entity_id: input_boolean.disable_home_away
      state: 'off'

  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.vacation_mode

        ##########################################################
        ## Turn On Vacation Mode when Thermostat set to Vacation
        ##########################################################

- alias: Vacation - Turn On when Thermostat set to Vacation
  id: 'vacation_turn_on_when_thermostat_set_to_vacation'

  trigger:
    - platform: state
      entity_id: sensor.thermostat_climate_mode
      to: 'vacation'

  condition:
    - condition: state
      entity_id: input_boolean.disable_home_away
      state: 'off'
    - condition: not
      conditions:
      - condition: state
        entity_id: group.household
        state: 'home'

  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.vacation_mode

        ##########################################################
        ## Vacation Lights On at Night
        ##########################################################

- alias: Vacation - Lights On at Night
  id: 'vacation_lights_on_at_night'

  trigger:
    - platform: state
      entity_id: sun.sun
      from: 'above_horizon'
      to: 'below_horizon'

  condition:
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'on'

  action:
    - delay:
        minutes: '{{ range(2, 20) | random }}'
    - service: light.turn_on
      entity_id:
        - light.kitchen_sink
      data:
        brightness_pct: 50
    - delay:
        minutes: '{{ range(2, 28) | random }}'
    - service: light.turn_on
      entity_id:
        - light.living_room_lamps
      data:
        brightness_pct: 75
        transition: 120
    - delay:
        minutes: '{{ range(2, 59) | random }}'
    - service: light.turn_on
      entity_id:
        - light.bedroom_ceiling
      data:
        brightness_pct: 25
        transition: 60
    - delay:
        minutes: '{{ range(2, 45) | random }}'
    - service: light.turn_on
      entity_id:
        - light.USER1_office_desk_lamp
        - light.USER1_office_desk_accent
      data:
        brightness_pct: 80

        ##########################################################
        ## Vacation Mode Lights off at Night
        ##########################################################

- alias: Vacation - Lights Off at Night
  id: 'vacation_lights_off_at_night'

  trigger:
    - platform: time
      at: '21:30:00'

  condition:
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'on'

  action:
    - delay:
        minutes: '{{ range(2, 32) | random }}'
    - service: light.turn_off
      entity_id:
        - light.kitchen_sink
    - delay:
        minutes: '{{ range(2, 59) | random }}'
    - service: light.turn_off
      entity_id:
        - light.living_room_lamps
    - delay:
        minutes: '{{ range(2, 30) | random }}'
    - service: light.turn_off
      entity_id:
        - light.bedroom_ceiling
    - delay:
        minutes: '{{ range(2, 45) | random }}'
    - service: light.turn_off
      entity_id:
        - light.USER1_office_desk_lamp
        - light.USER1_office_desk_accent