#################################################################
## Water Sensor Automations
#################################################################

        ##########################################################
        ## Send Notification for Water Detected Drain
        ##########################################################

- alias: Water Sensor - Basement Water Sensor Text Notification

  trigger:
    - platform: state
      entity_id: binary_sensor.basement_drain_water_sensor_liquid_detected
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: notify.ios_USER1s_iphone
      data:
        message: Water Detected in Basement!

        ##########################################################
        ## Send Notification for Water Detected Sump Pump
        ##########################################################

- alias: Water Sensor - Sump Pump Water Sensor Send Notification

  trigger:
    - platform: state
      entity_id: binary_sensor.sump_pump_water_sensor_liquid_detected
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: notify.ios_USER1s_iphone
      data:
        message: Water Detected in Sump Pump!

        ##########################################################
        ## Sound Alarm When Water Detected
        ##########################################################

- alias: Water Sensor -  Sound Alarm When Water Detected Siren

  trigger:
    - platform: state
      entity_id: binary_sensor.basement_drain_water_sensor_liquid_detected
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: input_boolean.disable_water_sensors
      state: 'off'

  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.alarm_tripped
    - service: switch.turn_on
      entity_id:
        - switch.siren

        ##########################################################
        ## Flash Lights when Water Detected
        ##########################################################

- alias: Water Sensor - Sound Alarm When Water Detected Lights

  trigger:
    - platform: state
      entity_id: binary_sensor.basement_drain_water_sensor_liquid_detected
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: input_boolean.disable_water_sensors
      state: 'off'

  action:
    - service: light.turn_on
      entity_id:
        - light.hue_lights
      data:
       brightness_pct: 100
       color_name: "blue"
    - service: light.turn_on
      entity_id:
        - light.hue_lights
      data:
       flash: long

        ##########################################################
        ## Water Sensor Audio Notification
        ##########################################################

- alias: Water Sensor - Basement Water Sensor

  trigger:
    - platform: state
      entity_id: binary_sensor.basement_drain_water_sensor_liquid_detected
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: input_boolean.disable_water_sensors
      state: 'off'
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: script.turn_on
      entity_id: script.say
      data:
        variables:
          master: 'media_player.sonos_living_room'
          where: 'media_player.sonos_media_center, media_player.sonos_living_room, media_player.sonos_dining_room, media_player.sonos_kitchen, media_player.sonos_bathroom, media_player.sonos_bedroom, media_player.sonos_USER1s_office, media_player.sonos_USER2s_office, media_player.sonos_basement'
          volume: '.9'
          what: 'Water Detected in Basement!'
