#################################################################
## Weather Based Automations
#################################################################

        ##########################################################
        ## Turn On First Floor Lights when Raining
        ##########################################################

- alias: Weather - Rain First Floor Lights On

  trigger:
    - platform: state
      entity_id: sensor.dark_sky_precip
      to: 'rain'

  condition:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: time
      after: '09:00'
    - condition: state
      entity_id: sun.sun
      state: 'above_horizon'
    - condition: state
      entity_id: binary_sensor.main_floor_occupancy
      state: 'on'
    - condition: state
      entity_id: input_boolean.disable_rainy_day
      state: 'off'
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: light.living_room_lights
      state: 'off'
    - condition: state
      entity_id: light.dining_room_lights
      state: 'off'
    - condition: state
      entity_id: light.kitchen_lights
      state: 'off'

  action:
    - service: light.turn_on
      entity_id:
        - light.living_room_lights
        - light.hallway_light
      data:
        color_temp: 447
        brightness_pct: 50
        transition: 300
    - service: light.turn_on
      entity_id:
        - light.kitchen_cabinets
        - light.dining_room_table
        - light.kitchen_sink
      data:
        brightness_pct: 1
    - service: light.turn_on
      entity_id:
        - light.globe
      data:
        color_name: blue
        brightness_pct: 15
        transition: 60

        ##########################################################
        ## Turn On USER2 Office when Raining
        ##########################################################

- alias: Weather - Rain USER2 Office Lights On

  trigger:
    - platform: state
      entity_id: sensor.dark_sky_precip
      to: 'rain'

  condition:
    - condition: state
      entity_id: binary_sensor.USER2_office_occupancy
      state: 'on'
    - condition: state
      entity_id: sun.sun
      state: 'above_horizon'
    - condition: state
      entity_id: input_boolean.disable_rainy_day
      state: 'off'
    - condition: state
      entity_id: device_tracker.USER2DEVICE
      state: 'home'
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: light.USER2_office_lights
      state: 'off'

  action:
    - service: light.turn_on
      entity_id:
        - light.USER2_office_lights
      data:
        transition: 300
        brightness_pct: 50
    - service: light.turn_on
      entity_id:
        - light.stairs
      data:
        transition: 10
        brightness_pct: 1
